### ISSUE TITLE
Add support for python 3.9

### ISSUE THREAD

**Issue by tsuga** [zappa/Zappa#1034]
## Context

AWS [announced](https://aws.amazon.com/jp/blogs/compute/python-3-9-runtime-now-available-in-aws-lambda/) that python 3.9 is available for Lamba runtime.

## Expected Behavior

Zappa should support python 3.9

## Actual Behavior

I got this error:
```
Zappa (and AWS Lambda) support the following versions of Python: ['3.6', '3.7', '3.8']
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/zappa_handler.py", line 24, in <module>
    from zappa.middleware import ZappaWSGIMiddleware
  File "/var/task/zappa/__init__.py", line 14, in <module>
    raise RuntimeError(err_msg)
```

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used:
* Operating System and Python version:
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.json`:

**Comment by opqpop** [comment]
bump, also need this, can someone please help stamp the fix which has been out for 20 days? 

https://github.com/zappa/Zappa/pull/1026

**Comment by Ryce** [comment]
Bump, need this one as well. Would be greatly appreciated 👍 

#1026
