### ISSUE TITLE
Lambda update fails with ResourceConflictException

### ISSUE THREAD

**Issue by illing2005** [zappa/Zappa#1041]
## Context

Since today the `zappa update` method fails with the following error:

```
Downloading and installing dependencies..
Packaging project as zip.
Uploading ***********-1631808391.tar.gz (50.2MiB)..
100% 52.6M/52.6M [00:00<00:00, 101MB/s] 
Uploading handler_***********-1631808473.zip (14.5MiB)..
100% 15.2M/15.2M [00:00<00:00, 43.1MB/s]
Updating Lambda function code..
Updating Lambda function configuration..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/root/repo/venv/lib/python3.6/site-packages/zappa/cli.py", line 2785, in handle
    sys.exit(cli.handle())
  File "/root/repo/venv/lib/python3.6/site-packages/zappa/cli.py", line 510, in handle
    self.dispatch_command(self.command, stage)
  File "/root/repo/venv/lib/python3.6/site-packages/zappa/cli.py", line 557, in dispatch_command
    self.update(self.vargs['zip'], self.vargs['no_upload'])
  File "/root/repo/venv/lib/python3.6/site-packages/zappa/cli.py", line 975, in update
    aws_kms_key_arn=self.aws_kms_key_arn,
  File "/root/repo/venv/lib/python3.6/site-packages/zappa/core.py", line 1203, in update_lambda_configuration
    'Mode': 'Active' if self.xray_tracing else 'PassThrough'
  File "/root/repo/venv/lib/python3.6/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/repo/venv/lib/python3.6/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the UpdateFunctionConfiguration operation: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-********:function:***********

==============
```

It seems like lambda introduced `function states` and the state needs to be checked during deployment.
https://forums.aws.amazon.com/thread.jspa?messageID=995846&#995846

In the error above this means that the state needs to be checked **after** _Updating Lambda function code_ and **before** _Updating Lambda function configuration_ 

Is there already a fix for this issue?

**Comment by vrbrito** [comment]
Facing the same problem over here.

**Comment by guilhermej** [comment]
same error here

**Comment by armando-herastang** [comment]
Same here! 😢

**Comment by jcastillejo1** [comment]
As a workaround, until October 1, you can opt-out.

**Comment by illing2005** [comment]
Thanks, @jcastillejo1! That saved my day!

Here are two prs that should fix this issue:
https://github.com/zappa/Zappa/pull/1042
https://github.com/zappa/Zappa/pull/992

**Comment by jayaaravind** [comment]
Hello,
   we are experiencing the same issues.  With the Oc 1st deadline coming up where the work-around will stop working, will these PRs be merged by then?
thanks for the help
Jaya

**Comment by roylanmartinez** [comment]
Hey I am facing the same issue.

**Comment by javulticat** [comment]
Resolved as of `v0.54.0` via #992

**Comment by FernandoCelmer** [comment]
> 

![image](https://user-images.githubusercontent.com/6262214/142893138-107b587a-55cf-4b20-89cc-170880ab0c51.png)

Both mechanisms work by adding a special string in the “Description” parameter of Lambda functions. You can add this string anywhere in this parameter. You can opt to add it to the prefix or suffix, or set the entire contents of the field. This parameter is processed at create or update in accordance with the requested action.

![image](https://user-images.githubusercontent.com/6262214/142893263-cff442b1-38a0-4336-b336-8e6b02f37317.png)

Link: https://aws.amazon.com/pt/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/

**Comment by mbiokyle29** [comment]
Sorry to revive this thread, but I am seeing some weird issues here still. On my local machine, updating to `0.54.1` fixed this issue (when manually running `zappa update`). However, in our CI pipeline on github actions, zappa deploy fails with a similar error:
```
Downloading and installing dependencies..
 - pydantic==1.8.2: Downloading

  0%|          | 0.00/13.7M [00:00<?, ?B/s]
 36%|███▌      | 4.93M/13.7M [00:00<00:00, 49.3MB/s]
 97%|█████████▋| 13.4M/13.7M [00:00<00:00, 69.9MB/s]
100%|██████████| 13.7M/13.7M [00:00<00:00, 66.8MB/s]
Packaging project as zip.
Uploading *******-1638573362.zip (28.0MiB)..

  0%|          | 0.00/29.4M [00:00<?, ?B/s]
  1%|          | 262k/29.4M [00:00<00:51, 566kB/s]
  4%|▎         | 1.05M/29.4M [00:00<00:14, 2.00MB/s]
 10%|▉         | 2.88M/29.4M [00:00<00:04, 5.33MB/s]
 24%|██▍       | 7.08M/29.4M [00:00<00:01, 12.0MB/s]
 44%|████▍     | 12.9M/29.4M [00:01<00:00, 20.8MB/s]
 60%|█████▉    | 17.6M/29.4M [00:01<00:00, 26.5MB/s]
 83%|████████▎ | 24.4M/29.4M [00:01<00:00, 36.6MB/s]
 99%|█████████▉| 29.1M/29.4M [00:01<00:00, 33.6MB/s]
Updating Lambda function code..
Oh no! An error occurred! :(

==============

100%|██████████| 29.4M/29.4M [00:01<00:00, 17.4MB/s]

Traceback (most recent call last):
==============
  File "/home/runner/.venv/lib/python3.8/site-packages/zappa/cli.py", line 3415, in handle
    sys.exit(cli.handle())
  File "/home/runner/.venv/lib/python3.8/site-packages/zappa/cli.py", line 588, in handle
    self.dispatch_command(self.command, stage)
  File "/home/runner/.venv/lib/python3.8/site-packages/zappa/cli.py", line 641, in dispatch_command
    self.update(
  File "/home/runner/.venv/lib/python3.8/site-packages/zappa/cli.py", line 1155, in update
    self.lambda_arn = self.zappa.update_lambda_function(**kwargs)
  File "/home/runner/.venv/lib/python3.8/site-packages/zappa/core.py", line 1284, in update_lambda_function
    response = self.lambda_client.update_function_code(**kwargs)
  File "/home/runner/.venv/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/runner/.venv/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the UpdateFunctionCode operation: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-west-2:***:function:******

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Zappa/Zappa
And join our Slack channel here: https://zappateam.slack.com
Love!,
 ~ Team Zappa!
 ```

I tried with 0.54.1 and 0.54.0 and no luck. Interestingly it seems like mine is failing during `Updating Lambda function code..`, vs the above failing after `Updating Lambda function configuration..`

**Comment by mbiokyle29** [comment]
Disregard the above! Another step in our CI process was calling `update_function_configuration` with out also doing a wait on `function_updated`. Not a zappa issue. Sorry about that!

**Comment by jgwinner** [comment]
@mbiokyle29 Hi Kyle, PMFJI, how did you setup the GitHub action? Raw shell, or did you use a GitHub integration? I only found one on the marketplace that was pretty underdocumented. :)

**Comment by mbiokyle29** [comment]
@jgwinner just opt'ed for raw shell stuff (still a bit hesitant to dive into 3rd party actions). Roughly:
```yaml
deploy:

  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: load pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements_dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: install pip deps
      run: |
        python -m venv ~/.venv
        source ~/.venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt --upgrade

    - name: zappa update
      run: |
        source ~/.venv/bin/activate
        zappa update $stage
```

**Comment by ohadbenita** [comment]
Still happen to us as well, using Zappa 0.54.1

```
Traceback (most recent call last):
  File "/root/project/venv/lib/python3.8/site-packages/zappa/cli.py", line 3415, in handle
    sys.exit(cli.handle())
  File "/root/project/venv/lib/python3.8/site-packages/zappa/cli.py", line 588, in handle
    self.dispatch_command(self.command, stage)
  File "/root/project/venv/lib/python3.8/site-packages/zappa/cli.py", line 641, in dispatch_command
    self.update(
  File "/root/project/venv/lib/python3.8/site-packages/zappa/cli.py", line 1162, in update
    self.lambda_arn = self.zappa.update_lambda_configuration(
  File "/root/project/venv/lib/python3.8/site-packages/zappa/core.py", line 1417, in update_lambda_configuration
    response = self.lambda_client.update_function_configuration(**kwargs)
  File "/root/project/venv/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/project/venv/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ServiceException: An error occurred (ServiceException) when calling the UpdateFunctionConfiguration operation (reached max retries: 4): An error occurred and the request cannot be processed.
```

**Comment by lsorber** [comment]
Confirming that we're also experiencing this issue with v0.54.1.

**Comment by rrcrahulroy** [comment]
Confirming having same issue with latest version

**Comment by rrcrahulroy** [comment]
after updating zappa and troposphere. I am getting AttributeError: 'Template' object has no attribute 'add_description'
