### ISSUE TITLE
keep_warm_callback not working, No module named 'handler'

### ISSUE THREAD

**Issue by opqpop** [zappa/Zappa#1115]
## Context
I get this error message for the keep_warm_callback that gets scheduled, and it has been going on since I used venv3.8 before the repo migration, and still going on to this day

```
[ERROR] ModuleNotFoundError: No module named 'handler'
Traceback (most recent call last):
  File "/code/zappa/handler.py", line 657, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/code/zappa/handler.py", line 254, in lambda_handler
    return handler.handler(event, context)
  File "/code/zappa/handler.py", line 389, in handler
    app_function = self.import_module_and_get_function(whole_function)
  File "/code/zappa/handler.py", line 245, in import_module_and_get_function
    app_module = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked

-- | --
```

My zappa_settings.json

```
        "aws_region": "us-east-1",
        "profile_name": "default",
        "project_name": "flueth",
        "s3_bucket": "zappa-lambda-docker-django",
        "django_settings": "flueth.settings",
        "environment_variables": {
            "INSTANTIATE_LAMBDA_HANDLER_ON_IMPORT": "true"
        },        
        "lambda_description": "Zappa + Docker + Django",
        "memory_size": 10240,
        "keep_warm": true,
```

Anyone know the issue? Are we supposed to use "zappa.handler.keep_warm_callback" here? Or do I need to set something else up with env paths or something?

https://github.com/zappa/Zappa/blob/master/zappa/cli.py#L1405

**Comment by souravjamwal77** [comment]
Hi @opqpop Can you please remove `INSTANTIATE_LAMBDA_HANDLER_ON_IMPORT` from your code and try again. Let me know if it works.

**Comment by opqpop** [comment]
Hmmm, tried that and same error still persists

**Comment by souravjamwal77** [comment]
Can you post your complete zappa_settings.json file?

**Comment by thommor** [comment]
@opqpop has the above fixed your issue?

**Comment by monkut** [comment]
stale, closing.
