### ISSUE TITLE
zappa deploy fails pointing to cryptography

### ISSUE THREAD

**Issue by vhiremath** [zappa/Zappa#1130]
When I try to deploy my project to AWS Lambda using zappa deploy, it fails constantly.
Note: "apigateway_enabled": true
## Context
zappa deploy fails.
"Zappa tail staging" shows following error:
```
c:\temp\tools-service>zappa tail
Calling tail for stage staging..
[1651763288229] Instancing..
[1651763293072] [INFO] 2022-05-05T15:08:13.071Z 4e3e0ccf-4f99-4dc4-8e0c-5052f5e3509b Found credentials in environment variables.
[1651763293356] [INFO] 2022-05-05T15:08:13.356Z 4e3e0ccf-4f99-4dc4-8e0c-5052f5e3509b Override settings for pynamo not available /etc/pynamodb/global_default_settings.py
[1651763293356] [INFO] 2022-05-05T15:08:13.356Z 4e3e0ccf-4f99-4dc4-8e0c-5052f5e3509b Using Default settings value
[1651763293515] [ERROR] ImportError: cannot import name 'x509' from 'cryptography.hazmat.bindings._rust' (unknown location)
Traceback (most recent call last):
  File "/var/task/handler.py", line 657, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 251, in lambda_handler
    handler = cls()
  File "/var/task/handler.py", line 148, in __init__
    self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
```

## Expected Behavior
deployment should succeed.

## Actual Behavior
[1651763293515] [ERROR] ImportError: cannot import name 'x509' from 'cryptography.hazmat.bindings._rust' (unknown location)
Traceback (most recent call last):

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: 0.54.1
* Operating System and Python version: windows. python3.8
* The output of `pip freeze`:
```aniso8601 @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/4c/d3/30/6fa42abad0bd12d7965d331fdd4b2dbcae2a721297c131c24feaef6d01/aniso8601-9.0.1-py2.py3-none-any.whl
argcomplete @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/a3/13/7b/65010ac0e64f16afb907c8099695aa11c16d1698259e7e333eb9f2e76e/argcomplete-2.0.0-py2.py3-none-any.whl
astroid @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/6a/e3/31/117537dc44ba369036da18ae7f5f943ef5ca46467c326793953d5ce178/astroid-2.3.3-py3-none-any.whl
atomicwrites @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/ca/84/dd/000dbc2864acca52a74a82da8b597c9e4778eb3fe64687a31a8095ad5f/atomicwrites-1.4.0-py2.py3-none-any.whl
attrs @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/9a/27/ab/6895b786f345452394b42c1fdbe863803d0396e675b632c01cb13cad92/attrs-21.4.0-py2.py3-none-any.whl
authorization @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/virtualenvs/debugtools-service-666tM4hd-py3.8/src/authorization
aws-xray-sdk @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/be/58/77/f820befa3b17737fc962652e4cc5fdf3c1a7025ea696805873e07fe76e/aws_xray_sdk-2.9.0-py2.py3-none-any.whl
blinker @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/ac/c9/9a/af51314a61113d4fce8a348f12d41891ffccec98eedf1df659ded71760/blinker-1.4.tar.gz
boto3 @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/71/0f/dd/f27aec81b6762f61c149721c29419c4fc07308b6e9fe3f81c952a7bb60/boto3-1.22.7-py3-none-any.whl
botocore @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/e4/cb/f2/f2b77ae6476ea7ad8eba66a47d9fcdb805cce632e4ffbe25d6aea9813e/botocore-1.25.7-py3-none-any.whl
Brotli @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/cc/9d/0d/822f7fe5824fcce1fa46d11f1a68958381ea9a74471014e241f0e05e0b/Brotli-1.0.9-cp38-cp38-win_amd64.whl
cachetools @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/f9/20/3d/b32baed65351f7bfb969d54b511441bab7950a0245cdb6d5bcb2a88dcc/cachetools-5.0.0-py3-none-any.whl
certifi @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/77/74/3e/daf57610ff13227e3b3f50a78487055f6ac94cc9363abd2463be34c5e9/certifi-2021.10.8-py2.py3-none-any.whl
cffi @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/3a/7f/6a/3c0ea0d733f7b12ab32dbe191215e0a6fdd24c45aeec8b9971f4588ad2/cffi-1.15.0-cp38-cp38-win_amd64.whl
cfn-flip @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/44/5f/ce/7be4512cb88ba3bdb048f2033f935522951944ca465c872f9582081495/cfn_flip-1.3.0-py3-none-any.whl
charset-normalizer @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/ae/14/8e/087a104edb7ec627884755272de815d8ee4fd53b8745fdb12a087dd2e1/charset_normalizer-2.0.12-py3-none-any.whl
chroma-common @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/virtualenvs/debugtools-service-666tM4hd-py3.8/src/chroma-common
click @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/30/bc/bf/e00ffd8f0edf0294942e70e80e42a839bd2649d2c5b864e6389e526d2a/click-7.1.2-py2.py3-none-any.whl
colorama @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/b0/f3/a3/cf94f06cbe1d286a25116cfe54d5a75cb1c4b54d15b2b1b4fc03a7f657/colorama-0.4.4-py2.py3-none-any.whl
coverage @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/a9/dc/9f/4d430fa8c89c3def398b5f7d6d2fc610b014a5f552399aa930a993d0d2/coverage-6.3.2-cp38-cp38-win_amd64.whl
cryptography @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/ff/fb/2c/367826bf18f100b07235f82c2b67d65d0a974da9bb3c3eb2e378f8a549/cryptography-37.0.2-cp36-abi3-win_amd64.whl
durationpy @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/da/24/0a/ed1a7ce02c7cc1d61c2539295bccca25aeb1dce21f083ed1c7231eec2b/durationpy-0.5.tar.gz
ecdsa @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/07/3c/9e/e8a7d1d0b55146ef78ef77603fe9bdd7ced45d4dcf379cdf59b7712af1/ecdsa-0.17.0-py2.py3-none-any.whl
Flask @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/0b/5a/9e/38b1bab936ade7d1bccb7f5c39bdbe0215cb26c1d40260765099e5af4c/Flask-1.1.4-py2.py3-none-any.whl
Flask-Compress @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/ae/c3/66/5fafebc50a7bb6afe4edd53642faf052eec1a31265219666182bf220f4/Flask_Compress-1.12-py3-none-any.whl
Flask-Cors @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/68/bd/c6/9b05e193427a1d6199aa2c920a95d20bf522d7caefd203a78632036868/Flask_Cors-3.0.10-py2.py3-none-any.whl
flask-restplus @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/9d/87/9a/21313f017dc82e8a4ab96483ecbbddec92ed625fd8f92016af2232a23c/flask_restplus-0.13.0-py2.py3-none-any.whl
flask-restx @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/7d/de/c8/4dd05ff86d25a41cdaaa5f1596a5a764812426c19bf872aaa95c1c17ef/flask_restx-0.5.1-py2.py3-none-any.whl
future @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/d9/62/dc/809bb3ddfe360ddc60ebb287ad6b0eaf71aef98937f0ea0c466d44aa19/future-0.18.2.tar.gz
hjson @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/97/a3/1e/32c074377dadd1610cf11f440d9a6499bc44c363c4b41573ae7ae4ce92/hjson-3.0.2-py3-none-any.whl
httpretty @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/c9/62/71/12b51bde35a17f907cabc2dc068633325dbc3ab4edbdb8e753c4143990/httpretty-1.1.4.tar.gz
idna @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/f7/09/c9/8e80952436ff87855ddff4891a35ecf913b2b5dc97911f02a070ff2b1f/idna-3.3-py3-none-any.whl
importlib-resources @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/d0/ea/79/9fc11cc342887b1d6e8e7ea23071c9f2e528b37f409222287880c9bd69/importlib_resources-5.7.1-py3-none-any.whl
iniconfig @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/ac/f9/da/e990ffcd9ec361a68676a5916e391286e1ea5d1b8907ae887e141a71f5/iniconfig-1.1.1-py2.py3-none-any.whl
isort @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/6e/4e/fa/c1a31b7a066920f2d2cebcdf14f804e3f48fc87e5d4c85ae4805b246b2/isort-4.3.21-py2.py3-none-any.whl
itsdangerous @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/ed/be/b7/3afa53339fde1838049443e48288a0348e1c636069b0c90f199510d48a/itsdangerous-1.1.0-py2.py3-none-any.whl
Jinja2 @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/1e/19/63/9b4675e143abad59de60e0e667815fd5e19dd0b28fc2815f9f957726d3/Jinja2-2.11.3-py2.py3-none-any.whl
jmespath @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/a6/b1/e0/623eaec6007fe9b9a20269d607049615f940793e62dd0e166a9f55e679/jmespath-1.0.0-py3-none-any.whl
jsonschema @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/30/83/fa/e1b84d857f5fea8c8f0ae52363fc452d5d57ac79acd5eae1e3d2839383/jsonschema-4.4.0-py3-none-any.whl
jwcrypto @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/52/4c/e0/f8ee1e5f5529c2435ab4c97fcac538f803337f23b36e1a369ae498c2a2/jwcrypto-0.8-py2.py3-none-any.whl
kappa @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/88/56/a4/a57ca177ff46f233fe4908259fe018f7781787b55dba2f5d6f1c9028bf/kappa-0.6.0.tar.gz
lazy-object-proxy @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/56/a6/ab/9d1da4e81fd4152d0f80284aa0ea0e5d183330ace565f0339e8e476337/lazy_object_proxy-1.4.3-cp38-cp38-win_amd64.whl
MarkupSafe @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/ef/85/da/babfbe141addbd28b04337744d2e8fb925ffb8d20adbd3dffcebc588e6/MarkupSafe-2.0.1-cp38-cp38-win_amd64.whl
mccabe @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/37/6e/69/4a33a4d6c80c775b1ee205face2c6e07b762c8602bb0f0d236ebe790c5/mccabe-0.6.1-py2.py3-none-any.whl
mockito @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/64/c2/21/e2f4ef211214cf849cb5e47f09234e3b053b450225ebe73292e6d9e597/mockito-1.3.0-py3-none-any.whl
packaging @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/7f/d5/4c/1d3c4776012fc0bbe1f86e69bde2c5e36d2d32caa2e4845ac1fc08ab3f/packaging-21.3-py3-none-any.whl
pep517 @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/83/81/99/cdc366fbf014f5e8f22fc491a82d8b8e2b7a397e376b6808d1bbad266b/pep517-0.12.0-py2.py3-none-any.whl
pip-tools @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/25/87/00/630fa4ca61095111e15e96f4d0a2ddea1a64abecc071e306a5333a66f2/pip_tools-6.6.0-py3-none-any.whl
placebo @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/03/be/f6/299b0ac0ad7a3c5b09d7d41dfa9c0a75d028282820b0c53445fdc67664/placebo-0.10.0.tar.gz
pluggy @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/38/05/d7/70e2b0d553c780097b692ed658b0f553a28f16028d848a98174b1a2249/pluggy-1.0.0-py2.py3-none-any.whl
py @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/ab/b4/c3/a3971fd0d6ab5a2e40a43ad7b809005422d7cf333f7be6ccdfe9002e1b/py-1.11.0-py2.py3-none-any.whl
pyasn1 @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/a6/f7/5e/59a43ec23ade0888631b3f24244da7f5d5a0b6b40849c86b8c6b4c54d1/pyasn1-0.4.8-py2.py3-none-any.whl
pycparser @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/7a/f7/3b/fd50e9d7e1c02d2d2e8631fca716f6b6ffe3742f322e4a170eb3f2f41b/pycparser-2.21-py2.py3-none-any.whl
PyJWE @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/f4/0b/d9/56b55f5eb244e1f5acb408d140b7e8245563c71b7ec234bad4cf17a386/PyJWE-1.0.0.tar.gz
pylint @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/33/9e/d5/7c616007d6e4718526afd819edd6ca5ab46504cce44b07c39841a8fffb/pylint-2.4.4-py3-none-any.whl
pynamodb @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/a9/c8/ec/81b2a6f8a729101dc017b966a71efb03e3f20f43d652cf118503c669a6/pynamodb-5.2.1-py3-none-any.whl
pyparsing @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/91/2a/6d/42a0f15168f41bcd87d73fe4a52da47c7c913303cee6b916e279c5fd58/pyparsing-3.0.8-py3-none-any.whl
pyrsistent @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/c2/63/74/6e8fd4d3298141b35f247a85e2a18ded8c388202298015ddcdc37f787d/pyrsistent-0.18.1-cp38-cp38-win_amd64.whl
pytest @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/76/83/a1/9c646bc48f4a8d27bc538584c264ea4090918e6233aeafc09bae62b912/pytest-7.1.2-py3-none-any.whl
pytest-cov @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/ce/cd/a2/2d987485d9ccd39e0e4c99f44afb2031232743eb1ec04c4ccf1c3d3b44/pytest_cov-3.0.0-py3-none-any.whl
python-dateutil @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/0f/f1/e2/e1d3399cea26388e2ed5b93ea3e7c137d2b4027c5ba14c64ab839294ed/python_dateutil-2.8.2-py2.py3-none-any.whl
python-jose @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/2a/c5/a7/85c6b2970f23ba0e6b0c5b2efb6560b02434022a1f56da478d1fc623f7/python_jose-3.3.0-py2.py3-none-any.whl
python-slugify @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/98/6e/00/73c9eee9767891e4ed06215cdc9918afcf103aad45133c041f6d125824/python_slugify-6.1.2-py2.py3-none-any.whl
pytz @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/a8/3e/6e/8a4977a399a303a3f7efcd4499130efd051d4eefb6535ab04c7391d1b6/pytz-2022.1-py2.py3-none-any.whl
PyYAML @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/f7/e8/05/c16a713e7ee8d7b7dff0acfe3bfd713a63078d60be83d2ebb0f09288c3/PyYAML-6.0-cp38-cp38-win_amd64.whl
requests @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/dc/17/bf/8d9779110a13421f6181028974b24800ec70f28bf9b311411e1868b8c7/requests-2.27.1-py2.py3-none-any.whl
rsa @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/73/0a/c4/2ebf484214eb26f696c3bd14ac3b561ac093bd9aff1692645bd5f73ca7/rsa-4.8-py3-none-any.whl
s3transfer @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/5c/ab/1b/2fbd71ad53aa8a0e0ae2297da508aa28029aa39c29feb1316f8743f449/s3transfer-0.5.2-py3-none-any.whl
sentry-sdk @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/38/5a/76/4a8e5f8b2aae8b15621af1ed3e3f6c5ec5f865b89caa2242da224bfd16/sentry_sdk-1.5.11-py2.py3-none-any.whl
simplejson @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/aa/f4/70/65cc87b5e69e4319d80685ed119637aebe329044216ebf7ac683e4d7d1/simplejson-3.17.6-cp38-cp38-win_amd64.whl
six @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/48/e6/04/8118155ae3ec3a16dd2a213bbf7a7d8a62c596b2e90f73a22c896269f1/six-1.16.0-py2.py3-none-any.whl
text-unidecode @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/9b/cc/f2/c615087594418f3b86c03fb83c56a1d3b673e89924d4bd0cece68a7615/text_unidecode-1.3-py2.py3-none-any.whl
toml @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/9f/8c/c3/7b4f6778d60f3c9fa11f8fd0e48243bbad25a04975e0a01006b6350594/toml-0.10.2-py2.py3-none-any.whl
tomli @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/36/bd/11/98fa2af866c73d00f2498ade62c7fcf28db8656714b7b7a44e9cb2f855/tomli-2.0.1-py3-none-any.whl
tqdm @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/0f/74/cd/a2ed528f2003187ed0adf3ad1f88faf43d991f72331e2c2f9c42766f24/tqdm-4.64.0-py2.py3-none-any.whl
troposphere @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/90/e2/6a/70c04c008696b29dfcb45f46860c04a32dd62d6cd181e0ed5a6f6c6393/troposphere-4.0.1-py3-none-any.whl
ucs @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/virtualenvs/debugtools-service-666tM4hd-py3.8/src/ucs
urllib3 @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/82/6d/7d/27c3eb08fd57859a15aa9472bf2acde15878f936b4283bae9b2ad55599/urllib3-1.26.9-py2.py3-none-any.whl
Werkzeug @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/e5/5c/53/8ad18e5b9adef2268bc7ad26f6b216177dcb0c6ab56fb87e7890c7ac0e/Werkzeug-0.16.1-py2.py3-none-any.whl
wrapt @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/0f/6d/f0/86578b9fcaa464b6648333d0e1e27754fc712410a83e58cdfad217b5c9/wrapt-1.11.2.tar.gz
wsgi-request-logger @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/3a/8c/e7/ff26e97f04fbdf572551bfb3187edc3eb0a8ab9665a0f570fb0965df3c/wsgi-request-logger-0.4.6.tar.gz
zappa @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/84/e4/0b/9cba8ef618861f5d2d31065f711f927404a4d8fcccc57c668210941bb6/zappa-0.54.1-py2.py3-none-any.whl
zipp @ file:///C:/Users/vhiremath/AppData/Local/pypoetry/Cache/artifacts/4f/ef/74/a2e3ed624c546651f2ae9baca2eec6d2597a5c87b8370870bab625340c/zipp-3.8.0-py3-none-any.whl
```
* Link to your project (optional):
* Your `zappa_settings.json`: 
```
{
    "staging": {
        "app_function": "app.app",
        "profile_name": "default",
        "project_name": "my-service",
        "runtime": "python3.8",
        "s3_bucket": "my-staging",
        "aws_region": "us-east-1",
        "cloudwatch_log_level": "ERROR",
        "cloudwatch_data_trace": false,
        "cloudwatch_metrics_enabled": true,
        "cors": true,
        "debug": true,
        "lambda_description": "My Service",
        "log_level": "INFO",
        "apigateway_enabled": true
    }
}
```

**Comment by monkut** [comment]
Are you using `zappa_packages` ?  If you are you might want  to try to remove it and see if it can deploy with a manylinux wheel.

**Comment by sridhar562345** [comment]
```
Unable to import module 'handler': /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/cryptography/hazmat/bindings/_rust.abi3.so)"}
```
@monkut facing the same issue in lambda `python3.7` runtime due to the download of incorrect manylinux wheel.

Refer:
- https://github.com/pyca/cryptography/issues/6390
- https://github.com/pyca/cryptography/issues/6391

**Comment by monkut** [comment]
This looks like a package build issue.  I assume most build on their systems and deploy to aws, where it appears that on packaging the wrong version will be picked/installed.  

The install method below may help resolve the installation/packaging issue.

https://github.com/pyca/cryptography/issues/6391#issuecomment-976172880
```
pipenv run pip install \                                                                                             
    --platform manylinux2010_x86_64 \
    --target=$(pipenv --venv)/lib/python3.9/site-packages \
    --implementation cp \
    --python 3.9 \
    --only-binary=:all: --upgrade \
    cryptography
```
> A note for people finding this after cryptography 38.0.0 is released: We no longer ship manylinux2010 wheels. You will instead need to target manylinux2014 or manylinux_2_17 at minimum (the latter is an alias for the former).
>

**Comment by monkut** [comment]
latest cryptography uses a different manylinux platform than list above.
Make sure a manylinux version is available for your desired lambda runtime.

manylinux handling is being updated in:
https://github.com/zappa/Zappa/issues/1249

closing this issue.
