### ISSUE TITLE
Issue while trying to install or download zappa without binary file

### ISSUE THREAD

**Issue by sridhar562345** [zappa/Zappa#1199]
## Expected Behavior

Should be able to download
## Actual Behavior

```
pip3.9 download --no-binary :all: zappa --no-deps
Looking in indexes: https://pypi.python.org/simple
Collecting zappa
  Downloading zappa-0.55.0.tar.gz (166 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.5/166.5 kB 893.5 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-download-2qug6bqt/zappa_d50c219a10d445f6916cf40967821092/setup.py", line 15, in <module>
          "{}{}".format(name, version.strip('"')) if version != '"*"' else name for name, version in pipfile["packages"].items()
        File "/usr/lib/python3.9/configparser.py", line 963, in __getitem__
          raise KeyError(key)
      KeyError: 'packages'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

## Possible Fix

The reason might be due to the incorrect parsing of `Pipfile` in `setup.py`
## Steps to Reproduce

``` 
pip3.9 download --no-binary :all: zappa --no-deps
```

## Your Environment

* Zappa version used: 0.55.0
* Operating System and Python version: Ubuntu 20.04, python3.9
* The output of `pip freeze`:
* Link to your project (optional):
* Your `zappa_settings.json`:

**Comment by monkut** [comment]
Seems that the Pipfile is not included in the built tar.

![image](https://user-images.githubusercontent.com/1135529/204514475-875c42f3-eaaf-4aa9-864b-4f6bccdca080.png)

**Comment by monkut** [comment]
Confirmed Pipfile is now included in the resulting pypi package.

![image](https://user-images.githubusercontent.com/1135529/205025508-fdcbc015-b793-44c7-b5ef-d1fd9048616a.png)


released in 0.56.0, closing.
