### ISSUE TITLE
import torch - breaks while using zappa for lambda

### ISSUE THREAD

**Issue by Aameer** [zappa/Zappa#1220]
## Context

I have a simple flask app where I am loading an ML model from s3 and doing a prediction using that. For this app I am using torch. It works locally on my system (mac 13.1 (22C65)), However, while using zappa to deploy it to lambda we notice an error , details are below:

``` bash
[1676294133276] [ERROR] UnboundLocalError: local variable 'cublas_path' referenced before assignment
Traceback (most recent call last):
  File "/var/task/handler.py", line 663, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 245, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 427, in handler
    app_function = self.import_module_and_get_function(whole_function)
  File "/var/task/handler.py", line 236, in import_module_and_get_function
    app_module = importlib.import_module(module)
  File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/gf-pm-serverless/gf_pm_lambda_prediction.py", line 64, in <module>
    import torch
  File "/tmp/gf-pm-serverless/torch/__init__.py", line 217, in <module>
    _load_global_deps()
  File "/tmp/gf-pm-serverless/torch/__init__.py", line 178, in _load_global_deps
    _preload_cuda_deps()
  File "/tmp/gf-pm-serverless/torch/__init__.py", line 158, in _preload_cuda_deps
    ctypes.CDLL(cublas_path)

```
## Expected Behavior

ideally if its working locally it should work on lambda as well. I made sure my local environment is python3.8 and lamdba environment is 3.8 as well. 

## Actual Behavior

import torch breaks. Error trace above

## Steps to Reproduce

1. use a flask app with torch on python3.8 ( i am on mac)
2. Deploy it in dev environment and try to invoke it.

## Your Environment

* Zappa version used: `zappa==0.56.1`
* Operating System and Python version: for lambda with python3.8 I guess its Amazon linux  2. Working on  mac 13.1 and  on ubuntu 20. 
* The output of `pip freeze`:
```bash
aiohttp==3.8.3
aiosignal==1.3.1
argcomplete==2.0.0
async-timeout==4.0.2
attrs==22.2.0
boto3==1.26.64
botocore==1.29.64
certifi==2022.12.7
cfn-flip==1.3.0
charset-normalizer==2.1.1
click==8.1.3
datasets==2.8.0
dill==0.3.6
durationpy==0.5
filelock==3.9.0
Flask==2.2.2
frozenlist==1.3.3
fsspec==2023.1.0
hjson==3.1.0
huggingface-hub==0.11.1
idna==3.4
importlib-metadata==6.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.2.0
kappa==0.6.0
MarkupSafe==2.1.2
multidict==6.0.4
multiprocess==0.70.14
numpy==1.24.1
packaging==22.0
pandas==1.5.3
Pillow==9.4.0
placebo==0.9.0
protobuf==3.20.1
pyarrow==10.0.1
python-dateutil==2.8.2
python-slugify==8.0.0
pytz==2022.7.1
PyYAML==6.0
regex==2022.10.31
requests==2.28.1
responses==0.18.0
s3transfer==0.6.0
scikit-learn==1.2.0
scipy==1.10.0
six==1.16.0
tensorboardX==2.5.1
text-unidecode==1.3
threadpoolctl==3.1.0
tokenizers==0.13.2
toml==0.10.2
torch==1.13.1
torchvision==0.14.1
tqdm==4.64.1
transformers==4.25.1
troposphere==4.3.0
typing_extensions==4.4.0
urllib3==1.26.13
Werkzeug==2.2.2
xxhash==3.2.0
yarl==1.8.2
zappa==0.56.1
zipp==3.12.1
```

* Link to your project (optional):
* Your `zappa_settings.json`: 
```json
{
     "dev": {
         "app_function": "gf_pm_lambda_prediction.app",
         "aws_region": "ap-south-1",
         "profile_name": "default",
         "project_name": "gf-pm-serverless",
         "runtime": "python3.8",
         "s3_bucket": "zappa-lambda-deployment",
         "slim_handler": true,
         "ephemeral_storage":10240,
         "memory_size": 3008,
         "environment_variables": {
             "FLASK_APP":"gf_pm_lambda_prediction.py"
         }
     },
     "dev_ap_southeast_1": {
         "aws_region": "ap-southeast-1",
         "extends": "dev"
     },
     "dev_ap_southeast_2": {
         "aws_region": "ap-southeast-2",
         "extends": "dev"
     },
     "dev_ca_central_1": {
         "aws_region": "ca-central-1",
         "extends": "dev"
     }
 }
 ```
 
 I even tried setting  environmental variable `CUDA_VISIBLE_DEVICES =""` on lambda, still no luck, I even updated `torch==1.13.1` in requirements.txt to `torch==1.13.1 --extra-index-url https://download.pytorch.org/whl/cpu`
 
For now I ended up moving to a dedicated ec2 instance (Ubuntu 20) and it worked.  However, would appreciate if I could do it via zappa in a server-less manner. Would really appreciate recommendations on this front. 
 
 Thanks,
 Aameer

**Comment by monkut** [comment]
The `ctypes.CDLL(cublas_path)` error suggests that the blas library can't be found.
It's probably an issue with packaging.  

You may want to consider building a docker based image and use that.  Or try building a lambda layer and attaching the layer.

https://aws.amazon.com/es/premiumsupport/knowledge-center/lambda-python-package-compatible/?nc1=h_ls

**Comment by monkut** [comment]
inactive, closing.
