### ISSUE TITLE
load_remote_project_archive fails

### ISSUE THREAD

**Issue by van4oza** [zappa/Zappa#1275]
load_remote_project_archive fails with any python and even clean install
## Context
I don't get why lambda can't be initialized

## Expected Behavior
deploy is ok

## Actual Behavior

```
[ERROR] ClientError: An error occurred (InvalidToken) when calling the GetObject operation: The provided token is malformed or otherwise invalid.
Traceback (most recent call last):
  File "/var/task/handler.py", line 657, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 241, in lambda_handler
    handler = global_handler or cls()
  File "/var/task/handler.py", line 98, in __init__
    self.load_remote_project_archive(project_archive_path)
  File "/var/task/handler.py", line 170, in load_remote_project_archive
    archive_on_s3 = s3.Object(remote_bucket, remote_file).get()
  File "/var/task/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/var/task/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/var/task/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

## Possible Fix
???

## Steps to Reproduce

default conf

## Your Environment

* Zappa version used: 0.58.0
* Operating System and Python version: 3.10
* The output of `pip freeze`:
```
aiohttp==3.8.3
aiosignal==1.3.1
appdirs==1.4.3
argcomplete==3.1.2
asgiref==3.7.2
async-timeout==4.0.2
asynctest==0.13.0
atomicwrites==1.4.1
attrs==22.1.0
Authlib==0.15.6
backports-abc==0.5
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.11.1
black==22.3.0
blessed==1.14.2
blessings==1.7
boto==2.42.0
boto3==1.28.55
botocore==1.31.55
bpython==0.16
Brotli==1.0.9
bs4==0.0.1
cachetools==5.2.0
cement==2.8.2
certifi==2023.7.22
cffi==1.15.1
cfgv==3.3.1
cfn-flip==1.3.0
chardet==3.0.4
charset-normalizer==2.1.1
click==8.1.7
clickhouse-driver==0.2.0
colorama==0.3.7
coreapi==2.3.3
coreschema==0.0.4
coverage==3.7.1
cryptography==3.4.8
cssselect==1.2.0
curtsies==0.2.11
dataclasses-json==0.5.9
defusedxml==0.7.1
distlib==0.3.6
dj-database-url==0.4.1
dj-static==0.0.6
Django==3.2
django-braces==1.11.0
django-cors-headers==3.4.0
django-dbconn-retry==0.1.7
django-extensions==1.7.7
django-multiselectfield==0.1.12
django-oauth-toolkit==1.1.0
django-rest-framework-social-oauth2 @ git+https://github.com/adamyala/django-rest-framework-social-oauth2@118111e7fbbfd441300ef0d387cd0f563b8b737e
django-s3direct==0.4.2
django-storages==1.5.0
django-unixdatetimefield==0.1.6
django-webpack-loader==0.6.0
djangorestframework==3.11.1
djangorestframework-queryfields==1.0.0
docker-py==1.7.2
dockerpty==0.4.1
docopt==0.6.2
docutils==0.13.1
durationpy==0.5
ecdsa==0.10
editdistance==0.5.3
elasticsearch==7.0.5
elasticsearch-dsl==7.1.0
Fabric==1.8.2
fake-useragent==1.0.0
feedparser==6.0.10
ffmpeg-python @ git+https://github.com/kkroening/ffmpeg-python@df129c7ba30aaa9ffffb81a48f53aa7253b0b4e6
filelock==3.8.0
flake8==4.0.1
foreman==0.9.7
free-proxy==1.0.6
frozenlist==1.3.3
future==0.18.2
fuzzysearch==0.7.3
fuzzywuzzy==0.18.0
gender-guesser==0.2.0
geoip2==4.5.0
google-api-core==1.33.1
google-api-python-client==1.12.8
google-auth==2.14.1
google-auth-httplib2==0.0.4
google-auth-oauthlib==0.4.2
googleapis-common-protos==1.56.4
greenlet==2.0.2
gunicorn==19.3.0
haversine==2.7.0
hjson==3.1.0
html2text==2020.1.16
htmlmin==0.1.12
httplib2==0.18.1
identify==2.5.9
idna==3.4
ifaddr==0.2.0
importlib-metadata==1.7.0
IP2Location==8.9.0
iso8601==1.1.0
isodate==0.6.1
itsdangerous==0.23
itypes==1.1.0
Jinja2==2.9.6
jmespath==1.0.1
joblib==1.2.0
kappa==0.6.0
keyring==10.3.2
keyrings.alt==2.2
librespot==0.0.9
lxml==4.9.3
m3u8==1.0.0
mailchimp3==3.0.2
MarkupSafe==2.1.3
marshmallow==3.19.0
marshmallow-enum==1.5.1
maxminddb==2.2.0
mccabe==0.6.1
mongoengine==0.20.0
more-itertools==8.13.0
multidict==6.0.2
mutagen==1.46.0
mypy-extensions==0.4.3
nltk==3.7
nodeenv==1.7.0
numpy==1.21.6
oauth2==1.9.0.post1
oauth2client==4.1.3
oauthlib==2.0.7
packaging==23.1
pandas==1.3.5
paramiko==1.12.2
parse==1.19.0
pathlib-mate==1.1.1
pathspec==0.9.0
placebo==0.9.0
platformdirs==2.5.4
podcastparser==0.6.4
pre-commit==2.18.1
prettytable==3.5.0
progress==1.6
protobuf==3.20.1
psycopg2-binary==2.9.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.8.0
pycparser==2.21
pycrypto==2.6.1
pycryptodome==3.18.0
pycryptodomex==3.17
pyee==8.2.2
pyflakes==2.4.0
Pygments==2.2.0
pygsheets==2.0.5
PyJWT==1.6.1
pymongo==3.10.0
PyOgg==0.6.14a1
pyparsing==2.2.0
pyppeteer==0.2.6
pyquery==1.4.3
python-dateutil==2.8.2
python-http-client==3.3.7
python-Levenshtein==0.12.2
python-slugify==8.0.1
python-social-auth==0.3.6
python-twitter-v2==0.8.1
python3-openid==3.1.0
pytz==2022.4
PyYAML==6.0.1
RandomWords==0.2.1
raven==6.9.0
regex==2022.10.31
requests==2.30.0
requests-aws4auth==0.9
requests-futures==0.9.7
requests-html==0.10.0
requests-oauthlib==0.8.0
rsa==4.9
s3transfer==0.7.0
selenium==3.141.0
semantic-version==2.5.0
sendgrid==6.1.2
sgmllib3k==1.0.0
singledispatch==3.4.0.3
six==1.16.0
slackclient==2.9.3
social-auth-app-django==2.1.0
social-auth-core==1.7.0
soupsieve==2.3.2.post1
SQLAlchemy==1.4.44
sqlalchemy-mate==1.4.28.4
sqlparse==0.4.3
static3==0.7.0
tabulate==0.7.5
termcolor==1.1.0
text-unidecode==1.3
timeout-decorator==0.5.0
toml==0.10.2
tomli==2.0.1
tornado==6.0.3
tqdm==4.66.1
troposphere==4.4.1
twitch-dl==1.21.0
typed-ast==1.5.4
typing-inspect==0.9.0
typing_extensions==4.4.0
tzlocal==2.1
uritemplate==3.0.0
urllib3==1.26.16
uszipcode==1.0.1
virtualenv==20.0.8
w3lib==2.0.1
wcwidth==0.1.7
websocket-client==1.5.1
websockets==9.1
Werkzeug==2.3.7
wsgi-request-logger==0.4.6
WTForms==1.0.5
yarl==1.8.1
yt-dlp==2023.7.6
zappa==0.58.0
zeroconf==0.62.0
zipp==3.10.0
```
* Link to your project (optional):
* Your `zappa_settings.json`: 

```
{
    "test3.10": {
        "aws_region": "us-east-1",
        "django_settings": "...",
        "profile_name": "...",
        "project_name": "...",
        "runtime": "python3.10",
        "s3_bucket": "created by Zappa",
        "slim_handler": true,
        "exclude": ["*.csv"],
        "include": [],
        "timeout_seconds": 900,
        "memory_size": 2048,
        "layers": [
          "arn:aws:lambda:us-east-1:...:layer:ffmpeg:2",
          "arn:aws:lambda:us-east-1:...:layer:yt-dlp:32",
          "arn:aws:lambda:us-east-1:...:layer:twitch-dl:1"
        ],
        "certificate_arn": "...",
        "domain": "...",
        "environment_variables": {
          "AWS_ACCESS_KEY_ID": "...",
          "AWS_SECRET_ACCESS_KEY": "...",
          "DJANGO_DATABASE": "...",
          "DJANGO_SETTINGS_MODULE": "...",
          "current_environment": "...",
          "django_secret_prod_key": "...",
          "aws_bucket": "..."
        },
        "cloudwatch_log_level": "ERROR",
        "cloudwatch_data_trace": false,
        "cloudwatch_metrics_enabled": false,
        "log_level": "ERROR"
    }
}
```

**Comment by monkut** [comment]
> ClientError: An error occurred (InvalidToken) when calling the GetObject operation: The provided token is malformed or otherwise invalid.

This seems to imply a permissions issue.  Make sure that the executionrole has access to the `load_remote_project_archive(project_archive_path)` location.
