### ISSUE TITLE
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 500 response code.

### ISSUE THREAD

**Issue by virendrasing365** [zappa/Zappa#1354]
getting internal server error and also lama function is getting more than 60 sec to execute 
zappa.setting.json:
{
    "staging": {

        "aws_region": "us-east-1",
        "django_settings": "src.core.settings",

        "aws_region": "us-east-1",  // Set the AWS region to where your Lambda function is deployed
        "django_settings": "src.core.settings",  // This is the Django settings module path
        "app_function": null,  // Replace with your actual app function, adjust as per your app's entry point
        "profile_name": "rankfirst",  // Keep this if you are using the profile named 'rankfirst'
        "project_name": "rankfirst-be",  // Project name remains the same
        "runtime": "python3.10",  // Keeping the current Python runtime, unless you need to switch to python3.9
        "s3_bucket": "zappa-43i76hijm",  // Bucket name set by Zappa, if this is the one to use
        "environment_variables": {
            "SECRET_NAME": "stage/rankfirst"  // Replace with your actual Secrets Manager secret name
        },
        "manage_roles": false,  // Set to false since you're using a custom IAM role
        "role_name": "LambdaSecretsManagerAccessRole",  // Replace with your actual created IAM role name
        "timeout_seconds": 60,  // Set timeout for Lambda function
        "memory_size": 128,  // Set memory size, adjust based on your requirements
        "slim_handler": true,  // Enable slim handler for faster deploys

        "exclude": [
            "boto3",
            "dateutil",
            "botocore",
            "s3transfer",
            "concurrent"

        ]

    }
}

**Comment by sridhar562345** [comment]
@virendrasing365 you can check the lambda cloudwatch logs to debug the issue.

Providing context for additional logs would be helpful.

**Comment by virendrasing365** [comment]
2024-10-07T03:11:58.612Z
INIT_START Runtime Version: python:3.10.v44 Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:76741dae0c08864e3cd3eb9ace8d0c3c3ac08b28fdd9ff64215e1526f3f28fdb
2024-10-07T03:14:55.085Z
START RequestId: f3817274-15b8-4751-9cd1-0503162bfb15 Version: $LATEST
2024-10-07T03:14:55.086Z
Instancing..
2024-10-07T03:15:55.219Z
2024-10-07T03:15:55.219Z f3817274-15b8-4751-9cd1-0503162bfb15 Task timed out after 60.13 seconds
2024-10-07T03:15:55.219Z
END RequestId: f3817274-15b8-4751-9cd1-0503162bfb15
2024-10-07T03:15:55.219Z
REPORT RequestId: f3817274-15b8-4751-9cd1-0503162bfb15 Duration: 60133.74 ms Billed Duration: 60000 ms Memory Size: 128 MB Max Memory Used: 120 MB Init Duration: 591.58 ms
2024-10-07T03:15:55.359Z
INIT_START Runtime Version: python:3.10.v44 Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:76741dae0c08864e3cd3eb9ace8d0c3c3ac08b28fdd9ff64215e1526f3f28fdb
2024-10-07T03:16:51.512Z
START RequestId: f3817274-15b8-4751-9cd1-0503162bfb15 Version: $LATEST
2024-10-07T03:16:51.513Z
Instancing..
2024-10-07T03:16:51.999Z
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
2024-10-07T03:16:51.999Z
[ERROR] ModuleNotFoundError: No module named 'asgiref' Traceback (most recent call last):   File "/var/task/handler.py", line 657, in lambda_handler     return LambdaHandler.lambda_handler(event, context)   File "/var/task/handler.py", line 241, in lambda_handler     handler = global_handler or cls()   File "/var/task/handler.py", line 150, in __init__     wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)   File "/var/task/zappa/ext/django_zappa.py", line 9, in get_django_wsgi     from django.core.wsgi import get_wsgi_application   File "/tmp/rankfirst-be/django/core/wsgi.py", line 2, in <module>     from django.core.handlers.wsgi import WSGIHandler   File "/tmp/rankfirst-be/django/core/handlers/wsgi.py", line 3, in <module>     from django.conf import settings   File "/tmp/rankfirst-be/django/conf/__init__.py", line 19, in <module>     from django.utils.deprecation import RemovedInDjango51Warning, RemovedInDjango60Warning   File "/tmp/rankfirst-be/django/utils/deprecation.py", line 4, in <module>     from asgiref.sync import iscoroutinefunction, markcoroutinefunction, sync_to_async
2024-10-07T03:16:52.039Z
END RequestId: f3817274-15b8-4751-9cd1-0503162bfb15
2024-10-07T03:16:52.039Z
REPORT RequestId: f3817274-15b8-4751-9cd1-0503162bfb15 Duration: 527.35 ms Billed Duration: 528 ms Memory Size: 128 MB Max Memory Used: 51 MB
2024-10-07T03:18:55.095Z
START RequestId: 1ebf5b6c-21e4-4fb6-9e6b-36599fd916f5 Version: $LATEST
2024-10-07T03:18:55.096Z
[DEBUG] 2024-10-07T03:18:55.096Z 1ebf5b6c-21e4-4fb6-9e6b-36599fd916f5 Zappa Event: {'time': '2024-10-07T03:18:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': '82e18568-fbad-93a9-c0d0-fe22fce309ee', 'kwargs': {}}
2024-10-07T03:18:55.097Z
[DEBUG] 2024-10-07T03:18:55.096Z 1ebf5b6c-21e4-4fb6-9e6b-36599fd916f5 Zappa Event: {}
2024-10-07T03:18:55.100Z
END RequestId: 1ebf5b6c-21e4-4fb6-9e6b-36599fd916f5
2024-10-07T03:18:55.100Z
REPORT RequestId: 1ebf5b6c-21e4-4fb6-9e6b-36599fd916f5 Duration: 5.55 ms Billed Duration: 6 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T03:18:58.146Z
START RequestId: f3817274-15b8-4751-9cd1-0503162bfb15 Version: $LATEST
2024-10-07T03:18:58.147Z
[DEBUG] 2024-10-07T03:18:58.147Z f3817274-15b8-4751-9cd1-0503162bfb15 Zappa Event: {'time': '2024-10-07T03:14:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': '4520cbb1-5802-0de5-7ca1-3ff4bb64ce50', 'kwargs': {}}
2024-10-07T03:18:58.147Z
[DEBUG] 2024-10-07T03:18:58.147Z f3817274-15b8-4751-9cd1-0503162bfb15 Zappa Event: {}
2024-10-07T03:18:58.148Z
END RequestId: f3817274-15b8-4751-9cd1-0503162bfb15
2024-10-07T03:18:58.148Z
REPORT RequestId: f3817274-15b8-4751-9cd1-0503162bfb15 Duration: 1.56 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T03:22:55.062Z
START RequestId: de9bbfb1-303d-4e62-acf2-cabfbad01466 Version: $LATEST
2024-10-07T03:22:55.062Z
[DEBUG] 2024-10-07T03:22:55.062Z de9bbfb1-303d-4e62-acf2-cabfbad01466 Zappa Event: {'time': '2024-10-07T03:22:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': '4d8c0618-a19a-92b5-e344-48668112222a', 'kwargs': {}}
2024-10-07T03:22:55.063Z
[DEBUG] 2024-10-07T03:22:55.063Z de9bbfb1-303d-4e62-acf2-cabfbad01466 Zappa Event: {}
2024-10-07T03:22:55.064Z
END RequestId: de9bbfb1-303d-4e62-acf2-cabfbad01466
2024-10-07T03:22:55.064Z
REPORT RequestId: de9bbfb1-303d-4e62-acf2-cabfbad01466 Duration: 1.68 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T03:26:54.918Z
START RequestId: 0c3effae-c2f4-4c88-a6b6-0726723e0491 Version: $LATEST
2024-10-07T03:26:54.918Z
[DEBUG] 2024-10-07T03:26:54.918Z 0c3effae-c2f4-4c88-a6b6-0726723e0491 Zappa Event: {'time': '2024-10-07T03:26:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': 'b566d38d-221c-e44d-b349-3b1ac98bc741', 'kwargs': {}}
2024-10-07T03:26:54.918Z
[DEBUG] 2024-10-07T03:26:54.918Z 0c3effae-c2f4-4c88-a6b6-0726723e0491 Zappa Event: {}
2024-10-07T03:26:54.919Z
END RequestId: 0c3effae-c2f4-4c88-a6b6-0726723e0491
2024-10-07T03:26:54.919Z
REPORT RequestId: 0c3effae-c2f4-4c88-a6b6-0726723e0491 Duration: 1.63 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T03:30:55.026Z
START RequestId: 5ad0b91c-6460-43e2-8c42-7d257bced223 Version: $LATEST
2024-10-07T03:30:55.026Z
[DEBUG] 2024-10-07T03:30:55.026Z 5ad0b91c-6460-43e2-8c42-7d257bced223 Zappa Event: {'time': '2024-10-07T03:30:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': 'bcea4cad-ad2d-9078-d27a-97e67bd7836d', 'kwargs': {}}
2024-10-07T03:30:55.027Z
[DEBUG] 2024-10-07T03:30:55.026Z 5ad0b91c-6460-43e2-8c42-7d257bced223 Zappa Event: {}
2024-10-07T03:30:55.027Z
END RequestId: 5ad0b91c-6460-43e2-8c42-7d257bced223
2024-10-07T03:30:55.027Z
REPORT RequestId: 5ad0b91c-6460-43e2-8c42-7d257bced223 Duration: 1.62 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T03:34:55.138Z
START RequestId: 6c1317bf-ef29-4b46-b451-c15cfcf03f40 Version: $LATEST
2024-10-07T03:34:55.139Z
[DEBUG] 2024-10-07T03:34:55.139Z 6c1317bf-ef29-4b46-b451-c15cfcf03f40 Zappa Event: {'time': '2024-10-07T03:34:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': '76de0cc1-effd-f7e5-f29f-bd3cb97aa554', 'kwargs': {}}
2024-10-07T03:34:55.139Z
[DEBUG] 2024-10-07T03:34:55.139Z 6c1317bf-ef29-4b46-b451-c15cfcf03f40 Zappa Event: {}
2024-10-07T03:34:55.140Z
END RequestId: 6c1317bf-ef29-4b46-b451-c15cfcf03f40
2024-10-07T03:34:55.140Z
REPORT RequestId: 6c1317bf-ef29-4b46-b451-c15cfcf03f40 Duration: 1.48 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T03:38:54.948Z
START RequestId: c950d9fc-fc28-42db-ad66-ebc2a9240960 Version: $LATEST
2024-10-07T03:38:54.948Z
[DEBUG] 2024-10-07T03:38:54.948Z c950d9fc-fc28-42db-ad66-ebc2a9240960 Zappa Event: {'time': '2024-10-07T03:38:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': 'dbe83c7d-9381-d234-3f60-b24b1879296f', 'kwargs': {}}
2024-10-07T03:38:54.948Z
[DEBUG] 2024-10-07T03:38:54.948Z c950d9fc-fc28-42db-ad66-ebc2a9240960 Zappa Event: {}
2024-10-07T03:38:54.949Z
END RequestId: c950d9fc-fc28-42db-ad66-ebc2a9240960
2024-10-07T03:38:54.949Z
REPORT RequestId: c950d9fc-fc28-42db-ad66-ebc2a9240960 Duration: 1.49 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T03:42:54.997Z
START RequestId: af0298e8-7a11-4c74-8f7f-643d94437d02 Version: $LATEST
2024-10-07T03:42:54.997Z
[DEBUG] 2024-10-07T03:42:54.997Z af0298e8-7a11-4c74-8f7f-643d94437d02 Zappa Event: {'time': '2024-10-07T03:42:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': 'fc110f79-ed8b-09fc-98a4-97eaf441f9ca', 'kwargs': {}}
2024-10-07T03:42:54.997Z
[DEBUG] 2024-10-07T03:42:54.997Z af0298e8-7a11-4c74-8f7f-643d94437d02 Zappa Event: {}
2024-10-07T03:42:55.010Z
END RequestId: af0298e8-7a11-4c74-8f7f-643d94437d02
2024-10-07T03:42:55.010Z
REPORT RequestId: af0298e8-7a11-4c74-8f7f-643d94437d02 Duration: 13.35 ms Billed Duration: 14 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T03:46:54.947Z
START RequestId: 329cf96d-e0d9-4c90-91dd-59c7f8e01f53 Version: $LATEST
2024-10-07T03:46:54.947Z
[DEBUG] 2024-10-07T03:46:54.947Z 329cf96d-e0d9-4c90-91dd-59c7f8e01f53 Zappa Event: {'time': '2024-10-07T03:46:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': '0c8589d7-99b5-149e-5c7a-df294453a86d', 'kwargs': {}}
2024-10-07T03:46:54.948Z
[DEBUG] 2024-10-07T03:46:54.948Z 329cf96d-e0d9-4c90-91dd-59c7f8e01f53 Zappa Event: {}
2024-10-07T03:46:54.951Z
END RequestId: 329cf96d-e0d9-4c90-91dd-59c7f8e01f53
2024-10-07T03:46:54.951Z
REPORT RequestId: 329cf96d-e0d9-4c90-91dd-59c7f8e01f53 Duration: 4.10 ms Billed Duration: 5 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T03:50:55.001Z
START RequestId: 694bc6d8-a694-430a-8aa2-976335e0b0c4 Version: $LATEST
2024-10-07T03:50:55.001Z
[DEBUG] 2024-10-07T03:50:55.001Z 694bc6d8-a694-430a-8aa2-976335e0b0c4 Zappa Event: {'time': '2024-10-07T03:50:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': 'fd5cde00-43d9-1993-a0f5-4e837538936c', 'kwargs': {}}
2024-10-07T03:50:55.001Z
[DEBUG] 2024-10-07T03:50:55.001Z 694bc6d8-a694-430a-8aa2-976335e0b0c4 Zappa Event: {}
2024-10-07T03:50:55.013Z
END RequestId: 694bc6d8-a694-430a-8aa2-976335e0b0c4
2024-10-07T03:50:55.013Z
REPORT RequestId: 694bc6d8-a694-430a-8aa2-976335e0b0c4 Duration: 11.81 ms Billed Duration: 12 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T03:54:54.887Z
START RequestId: e16c836a-86a0-4c84-a193-0ed782391114 Version: $LATEST
2024-10-07T03:54:54.888Z
[DEBUG] 2024-10-07T03:54:54.888Z e16c836a-86a0-4c84-a193-0ed782391114 Zappa Event: {'time': '2024-10-07T03:54:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': 'b283d608-37cd-c5ac-fd69-ed0084ebd299', 'kwargs': {}}
2024-10-07T03:54:54.888Z
[DEBUG] 2024-10-07T03:54:54.888Z e16c836a-86a0-4c84-a193-0ed782391114 Zappa Event: {}
2024-10-07T03:54:54.889Z
END RequestId: e16c836a-86a0-4c84-a193-0ed782391114
2024-10-07T03:54:54.889Z
REPORT RequestId: e16c836a-86a0-4c84-a193-0ed782391114 Duration: 1.53 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T03:58:54.972Z
START RequestId: 6a72ed0b-17b4-4c35-a2d0-01a92fc6f438 Version: $LATEST
2024-10-07T03:58:54.972Z
[DEBUG] 2024-10-07T03:58:54.972Z 6a72ed0b-17b4-4c35-a2d0-01a92fc6f438 Zappa Event: {'time': '2024-10-07T03:58:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': 'b25e9d3a-7ca8-4646-f21c-2963d12a712b', 'kwargs': {}}
2024-10-07T03:58:54.973Z
[DEBUG] 2024-10-07T03:58:54.973Z 6a72ed0b-17b4-4c35-a2d0-01a92fc6f438 Zappa Event: {}
2024-10-07T03:58:54.974Z
END RequestId: 6a72ed0b-17b4-4c35-a2d0-01a92fc6f438
2024-10-07T03:58:54.974Z
REPORT RequestId: 6a72ed0b-17b4-4c35-a2d0-01a92fc6f438 Duration: 1.81 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T04:02:54.989Z
START RequestId: 93cc730c-57dc-4c89-bba1-8bf5110e6f71 Version: $LATEST
2024-10-07T04:02:54.990Z
[DEBUG] 2024-10-07T04:02:54.990Z 93cc730c-57dc-4c89-bba1-8bf5110e6f71 Zappa Event: {'time': '2024-10-07T04:02:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': 'f6b6ebe3-2094-0088-d0f2-ed22515f2aaa', 'kwargs': {}}
2024-10-07T04:02:54.990Z
[DEBUG] 2024-10-07T04:02:54.990Z 93cc730c-57dc-4c89-bba1-8bf5110e6f71 Zappa Event: {}
2024-10-07T04:02:54.998Z
END RequestId: 93cc730c-57dc-4c89-bba1-8bf5110e6f71
2024-10-07T04:02:54.998Z
REPORT RequestId: 93cc730c-57dc-4c89-bba1-8bf5110e6f71 Duration: 8.46 ms Billed Duration: 9 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T04:06:54.968Z
START RequestId: 913a1a1a-6642-46b5-8596-f047ae232941 Version: $LATEST
2024-10-07T04:06:54.968Z
[DEBUG] 2024-10-07T04:06:54.968Z 913a1a1a-6642-46b5-8596-f047ae232941 Zappa Event: {'time': '2024-10-07T04:06:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': '94e71e0b-e207-7bd5-2a3f-5937f45122f5', 'kwargs': {}}
2024-10-07T04:06:54.969Z
[DEBUG] 2024-10-07T04:06:54.968Z 913a1a1a-6642-46b5-8596-f047ae232941 Zappa Event: {}
2024-10-07T04:06:54.969Z
END RequestId: 913a1a1a-6642-46b5-8596-f047ae232941
2024-10-07T04:06:54.969Z
REPORT RequestId: 913a1a1a-6642-46b5-8596-f047ae232941 Duration: 1.48 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T04:10:54.851Z
START RequestId: eb99ccd1-08ad-4b98-b62c-366645de2bfc Version: $LATEST
2024-10-07T04:10:54.852Z
[DEBUG] 2024-10-07T04:10:54.852Z eb99ccd1-08ad-4b98-b62c-366645de2bfc Zappa Event: {'time': '2024-10-07T04:10:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': '959b3f45-002b-c921-5799-94a561e0287b', 'kwargs': {}}
2024-10-07T04:10:54.852Z
[DEBUG] 2024-10-07T04:10:54.852Z eb99ccd1-08ad-4b98-b62c-366645de2bfc Zappa Event: {}
2024-10-07T04:10:54.861Z
END RequestId: eb99ccd1-08ad-4b98-b62c-366645de2bfc
2024-10-07T04:10:54.861Z
REPORT RequestId: eb99ccd1-08ad-4b98-b62c-366645de2bfc Duration: 10.00 ms Billed Duration: 11 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T04:14:54.958Z
START RequestId: 77081ba6-a4e3-4108-9ff3-302b97b8f098 Version: $LATEST
2024-10-07T04:14:54.959Z
[DEBUG] 2024-10-07T04:14:54.959Z 77081ba6-a4e3-4108-9ff3-302b97b8f098 Zappa Event: {'time': '2024-10-07T04:14:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': '381daa54-eb7e-fb42-110d-229de401b9bc', 'kwargs': {}}
2024-10-07T04:14:54.959Z
[DEBUG] 2024-10-07T04:14:54.959Z 77081ba6-a4e3-4108-9ff3-302b97b8f098 Zappa Event: {}
2024-10-07T04:14:54.960Z
END RequestId: 77081ba6-a4e3-4108-9ff3-302b97b8f098
2024-10-07T04:14:54.960Z
REPORT RequestId: 77081ba6-a4e3-4108-9ff3-302b97b8f098 Duration: 1.63 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T04:18:54.936Z
START RequestId: e58f1bb3-a6b7-472c-852b-320963e82867 Version: $LATEST
2024-10-07T04:18:54.937Z
[DEBUG] 2024-10-07T04:18:54.936Z e58f1bb3-a6b7-472c-852b-320963e82867 Zappa Event: {'time': '2024-10-07T04:18:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': '73280db5-aee3-c9e5-405e-5e48ac7649c5', 'kwargs': {}}
2024-10-07T04:18:54.937Z
[DEBUG] 2024-10-07T04:18:54.937Z e58f1bb3-a6b7-472c-852b-320963e82867 Zappa Event: {}
2024-10-07T04:18:54.938Z
END RequestId: e58f1bb3-a6b7-472c-852b-320963e82867
2024-10-07T04:18:54.938Z
REPORT RequestId: e58f1bb3-a6b7-472c-852b-320963e82867 Duration: 1.74 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T04:22:54.856Z
START RequestId: 17dc7118-14cc-49c0-a897-8a594538088c Version: $LATEST
2024-10-07T04:22:54.857Z
[DEBUG] 2024-10-07T04:22:54.857Z 17dc7118-14cc-49c0-a897-8a594538088c Zappa Event: {'time': '2024-10-07T04:22:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': 'b9fad03d-dc7f-489e-5cb1-5ca1fa5b1e5b', 'kwargs': {}}
2024-10-07T04:22:54.857Z
[DEBUG] 2024-10-07T04:22:54.857Z 17dc7118-14cc-49c0-a897-8a594538088c Zappa Event: {}
2024-10-07T04:22:54.858Z
END RequestId: 17dc7118-14cc-49c0-a897-8a594538088c
2024-10-07T04:22:54.858Z
REPORT RequestId: 17dc7118-14cc-49c0-a897-8a594538088c Duration: 1.71 ms Billed Duration: 2 ms Memory Size: 128 MB Max Memory Used: 52 MB
2024-10-07T04:26:54.921Z
START RequestId: 45857071-5d78-4d66-8c79-ac26f5b98d31 Version: $LATEST
2024-10-07T04:26:54.921Z
[DEBUG] 2024-10-07T04:26:54.921Z 45857071-5d78-4d66-8c79-ac26f5b98d31 Zappa Event: {'time': '2024-10-07T04:26:14Z', 'detail-type': 'Scheduled Event', 'source': 'aws.events', 'account': '156041405902', 'region': 'us-east-1', 'detail': {}, 'version': '0', 'resources': ['arn:aws:events:us-east-1:156041405902:rule/rankfirst-be-staging-zappa-keep-warm-handler.keep_warm_callback'], 'id': '88e0c8d4-21f7-afe0-3d15-c3a986dd4957', 'kwargs': {}}
2024-10-07T04:26:54.922Z
[DEBUG] 2024-10-07T04:26:54.922Z 45857071-5d78-4d66-8c79-ac26f5b98d31 Zappa Event: {}
2024-10-07T04:26:54.927Z
END RequestId: 45857071-5d78-4d66-8c79-ac26f5b98d31
2024-10-07T04:26:54.927Z
REPORT RequestId: 45857071-5d78-4d66-8c79-ac26f5b98d31 Duration: 6.07 ms Billed Duration: 7 ms Memory Size: 128 MB Max Memory Used: 52 MB

**Comment by monkut** [comment]
Your code is failing with an import error, `asgiref`.  Make sure it's included in your built package/env.

```
[ERROR] ModuleNotFoundError: No module named 'asgiref' Traceback (most recent call last): File "/var/task/handler.py", line 657, in lambda_handler return LambdaHandler.lambda_handler(event, context) File "/var/task/handler.py", line 241, in lambda_handler handler = global_handler or cls() File "/var/task/handler.py", line 150, in init wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS) File "/var/task/zappa/ext/django_zappa.py", line 9, in get_django_wsgi from django.core.wsgi import get_wsgi_application File "/tmp/rankfirst-be/django/core/wsgi.py", line 2, in from django.core.handlers.wsgi import WSGIHandler File "/tmp/rankfirst-be/django/core/handlers/wsgi.py", line 3, in from django.conf import settings File "/tmp/rankfirst-be/django/conf/init.py", line 19, in from django.utils.deprecation import RemovedInDjango51Warning, RemovedInDjango60Warning File "/tmp/rankfirst-be/django/utils/deprecation.py", line 4, in from asgiref.sync import iscoroutinefunction, markcoroutinefunction, sync_to_async
```

However, it looks like you are attempting to use async with zappa, which isn't supported atm.
