### ISSUE TITLE
[Migrated] CloudFormation stack missing, an error occurred! :(

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#415]
Originally from: https://github.com/Miserlou/Zappa/issues/1067 by [nautilus28](https://github.com/nautilus28)

It looks like a bug happened when CloudFormation was not enabled.

Calling update for stage dev..
Downloading and installing dependencies...
Packaging project as zip.
Uploading magsoc-javascri-dev-1503661683.zip (5.7MiB)..
Updating Lambda function code..
Updating Lambda function configuration..
Uploading magsoc-javascri-dev-template-1503661725.json (1.6KiB)..
CloudFormation stack missing, re-deploy to enable updates
Oh no! An error occurred! :(
```
==============

Traceback (most recent call last):
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/zappa/cli.py", line 2495, in handle
    sys.exit(cli.handle())
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/zappa/cli.py", line 477, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/zappa/cli.py", line 521, in dispatch_command
    self.update()
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/zappa/cli.py", line 909, in update
    self.zappa.add_binary_support(api_id=api_id, cors=self.cors)
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/zappa/core.py", line 1325, in add_binary_support
    restApiId=api_id
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/botocore/client.py", line 531, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/botocore/client.py", line 586, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/canhduong/.virtualenvs/magsoc.WebClient/lib/python3.6/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter restApiId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

**Comment by danaki** [comment]
Same issue here. Probably helps disabling
```
"binary_support": false
```

**Comment by monkut** [comment]
old migrated issue, consider resolved.

closing.
