### ISSUE TITLE
[Migrated] Deployed flask endpoint not working:  [run_wsgi_app TypeError: 'NoneType' object is not callable] App function file missing in Lamda zip package

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#526]
Originally from: https://github.com/Miserlou/Zappa/issues/1396 by [NakedKoala](https://github.com/NakedKoala)

## Context
I am trying to deploy my deep learning model to lambda. The entire deployment package is over 1 GB. I am using slim-handler.   

The app function file looks like this:

```
import logging
from flask import Flask
from flask import request
from flask import json
from model import TacoModel
from utils import image
from keras.preprocessing.image import img_to_array
import numpy as np

app = Flask(__name__)
logging.basicConfig()
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
taco_model = TacoModel()

@app.route('/', methods=['GET'])
def index():
    path = "data/"
    img = image.load_img(path+"test/unknown/hotdog679.JPEG",target_size=(224, 224))
    img = np.array([img_to_array(img)])
    res = taco_model.predict(img)
    return json.dumps(res)



if __name__ == '__main__':
    app.run()
 

```

Everything runs fine locally. When I curl my local server, I am able to get back the expected response. 

The zappa deployment was successful and without error.  But get request produces

```
{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 452, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/private/var/folders/kl/35lz1q3x2gs0y0r_1njxfd0m0000gn/T/pip-build-R7GWCg/Werkzeug/werkzeug/wrappers.py\", line 903, in from_app\\n', '  File \"/private/var/folders/kl/35lz1q3x2gs0y0r_1njxfd0m0000gn/T/pip-build-R7GWCg/Werkzeug/werkzeug/wrappers.py\", line 57, in _run_wsgi_app\\n', '  File \"/private/var/folders/kl/35lz1q3x2gs0y0r_1njxfd0m0000gn/T/pip-build-R7GWCg/Werkzeug/werkzeug/test.py\", line 884, in run_wsgi_app\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}
``` 

## Expected Behavior

Endpoint should work and return a dummy prediction on get request

## Actual Behavior

Get request failed. Produce the above error

## Possible Fix

I have tried clean up my virtualenv  & recreated virtualenv and re-deploy. Error still persists

zappa tail reveals this error

```
[1518497133157] No module named my_app: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 509, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 237, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 129, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
  __import__(name)
ImportError: No module named my_app
```
I tried exporting my lambda zip package. Upon inspection , my flask app function file is missing in the deployment package.  I am new to Zappa, but this looks wrong to me.  So I manually added the app function file and re-zip & upload.  But the get request still broke and zappa tail returns some different error.

Is something wrong during the packaging step ?

## Steps to Reproduce
live link
https://knbxmrhkt0.execute-api.us-west-2.amazonaws.com/dev

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version:  MacOS python 2.7
* The output of `pip freeze`:
```
absl-py==0.1.10
appnope==0.1.0
argcomplete==1.9.2
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0.post1
base58==0.2.4
bcolz==1.1.2
bleach==2.1.2
boto3==1.5.27
botocore==1.8.41
certifi==2018.1.18
cfn-flip==1.0.0
chardet==3.0.4
click==6.7
configparser==3.5.0
cycler==0.10.0
decorator==4.2.1
docutils==0.14
durationpy==0.5
entrypoints==0.2.3
enum34==1.1.6
Flask==0.12.2
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.1.1
h5py==2.7.1
hjson==3.0.1
html5lib==0.9999999
idna==2.6
ipykernel==4.8.1
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.1.1
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
kappa==0.6.0
Keras==1.2.2
lambda-packages==0.19.0
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.1.2
mistune==0.8.3
mock==2.0.0
mpmath==1.0.0
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.4.0
numpy==1.14.0
pandas==0.22.0
pandocfilters==1.4.2
pathlib2==2.3.0
pbr==3.1.1
pexpect==4.4.0
pickleshare==0.7.4
Pillow==5.0.0
placebo==0.8.1
prompt-toolkit==1.0.15
protobuf==3.5.1
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.6.1
python-slugify==1.2.4
pytz==2018.3
PyYAML==3.12
pyzmq==17.0.0
qtconsole==4.3.1
requests==2.18.4
s3transfer==0.1.12
scandir==1.7
scikit-learn==0.19.1
scipy==1.0.0
Send2Trash==1.4.2
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
subprocess32==3.2.7
sympy==1.1.1
tensorflow==1.5.0
tensorflow-tensorboard==1.5.1
terminado==0.8.1
testpath==0.3.1
Theano==1.0.1
toml==0.9.4
tornado==4.5.3
tqdm==4.19.1
traitlets==4.3.2
troposphere==2.2.0
Unidecode==1.0.22
urllib3==1.22
wcwidth==0.1.7
Werkzeug==0.12
widgetsnbextension==3.1.3
wsgi-request-logger==0.4.6
zappa==0.45.1
```

* Link to your project (optional):
* Your `zappa_settings.py`: 
```
{
    "dev": {
        "app_function": "my_app.app",
        "aws_region": "us-west-2",
        "profile_name": "default",
        "project_name": "freshstart3",
        "runtime": "python2.7",
        "s3_bucket": "[redacted]",
        "slim_handler": true
    }
}
```

**Comment by monkut** [comment]
configuration error assumed.

closing.
