### ISSUE TITLE
[Migrated] ModuleNotFoundError: No module named 'mysql'

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#529]
Originally from: https://github.com/Miserlou/Zappa/issues/1401 by [jsahoo](https://github.com/jsahoo)

## Context
I'm trying to use [MySQL Connector/Python](https://dev.mysql.com/downloads/connector/python/) with Zappa but keep getting `ModuleNotFoundError: No module named 'mysql'` after deploying. Everything works fine locally, the error only occurs on Lambda.

I'm installing mysql-connector-python from source URL:
`pip install https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-2.1.7.tar.gz`

I also tried uninstalling `mysql-connector-python` and instead installed `mysql-connector-python-rf` via `pip install mysql-connector-python-rf`. I get the exact same issue, `ModuleNotFoundError: No module named 'mysql'` on Lambda (again, it works perfectly locally).

I am running Zappa from a virtual environment and am using Python 3.6.

I thought that the issue might be related to https://github.com/Miserlou/Zappa/issues/319, so I tried to create a wheel from the Platform Independent ZIP archive (from MySQL's [download page](https://dev.mysql.com/downloads/connector/python/)). But every time I tried to do `python setup.py sdist bdist_wheel` I got `error: invalid command 'bdist_wheel'`. Spent a fair amount of time trying to get that to work before giving up.

Update: Interestingly enough, I tried using `"use_precompiled_packages": false` and no longer got `ModuleNotFoundError: No module named 'mysql'`. However, I then ended up getting:

```
Traceback (most recent call last):
  File "/var/task/handler.py", line 509, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 237, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 129, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/var/task/application.py", line 6, in <module>
  from PIL import Image
  File "/var/task/PIL/Image.py", line 58, in <module>
  from . import _imaging as core
ImportError: cannot import name '_imaging'
```

**Comment by monkut** [comment]
If a package needs to be built, make sure it has a manylinux package for the desired release.

stale, closing.
