### ISSUE TITLE
[Migrated] Attempted relative import with no known parent package when deployed to Amazon Web Services

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#538]
Originally from: https://github.com/Miserlou/Zappa/issues/1426 by [kyeljmd](https://github.com/kyeljmd)

I am developing a flask app locally, and I am using relative imports for my app. Here's my directory structure.

here's my app.py

```
from flask import Flask
from flask import request

from .dataproviders import provider
from .usecase import useCases


import json
import psycopg2

import os


app = Flask(__name__)
conn = None
cognito_data_provider = None
admin_usecase = None
##Initialize Services and dependencies
try:
    conn = psycopg2.connect(
        database=os.getenv('DATABASE_NAME'),
        user=os.getenv('DATABASE_USER'),
        password=os.getenv('DATABASE_PASSWORD'),
        host=os.getenv('DATABASE_HOST'),
        port=os.getenv('DATABASE_PORT'))

    cognito_data_provider = provider.CognitoDataProvider()
    admin_usecase = useCases.AdminUseCase(conn, cognito_data_provider)
except Exception as e:
    print(">>>> Error encountered setting up application depnedencies")


@app.route("/")
def hello():
    return admin_usecase.mes()
```

And here's my directory structure.

[Directory Structure](https://imgur.com/GFEu9bH)

Everything is running welll locally, however upon deploying it to AWS using zappa. produces this cloudwatch error.

`attempted relative import with no known parent package: ImportError
Traceback (most recent call last):
File "/var/task/handler.py", line 509, in lambda_handler
return LambdaHandler.lambda_handler(event, context)
File "/var/task/handler.py", line 237, in lambda_handler
handler = cls()
File "/var/task/handler.py", line 129, in __init__
self.app_module = importlib.import_module(self.settings.APP_MODULE)
File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 978, in _gcd_import
File "<frozen importlib._bootstrap>", line 961, in _find_and_load
File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
File "/var/task/app.py", line 4, in <module>
from .dataproviders import provider
ImportError: attempted relative import with no known parent package`

I am currently working on virtualenvwrapper in windows

**Comment by flozi00** [comment]
same here
any workaround for this ?
