### ISSUE TITLE
[Migrated] Pip 10 compatibility issues

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#560]
Originally from: https://github.com/Miserlou/Zappa/issues/1478 by [jleclanche](https://github.com/jleclanche)

Pip 10 was just released and I'm now getting this with it:

```pytb

12:15:05 Traceback (most recent call last):
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py", line 2610, in handle
12:15:05     sys.exit(cli.handle())
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py", line 505, in handle
12:15:05     self.dispatch_command(self.command, stage)
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py", line 549, in dispatch_command
12:15:05     self.update(self.vargs['zip'], self.vargs['no_upload'])
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py", line 877, in update
12:15:05     self.create_package()
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/cli.py", line 2171, in create_package
12:15:05     disable_progress=self.disable_progress
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/core.py", line 595, in create_lambda_zip
12:15:05     installed_packages = self.get_installed_packages(site_packages, site_packages_64)
12:15:05   File "/var/lib/jenkins/workspace/Deploy-Twitch-EBS-Lambda/.tox/jenkins_build/venv-deploy/lib/python3.6/site-packages/zappa/core.py", line 751, in get_installed_packages
12:15:05     pip.get_installed_distributions()
12:15:05 AttributeError: module 'pip' has no attribute 'get_installed_distributions'
12:15:05 Build step 'Execute shell' marked build as failure
12:15:05 Finished: FAILURE
```

Workaround: force install pip==9.0.3.

**Comment by monkut** [comment]
old migrated issue, considered resolved.

closing.
