### ISSUE TITLE
[Migrated] zappa deploy: region missing from zappa_settings.json created by zappa init

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#603]
Originally from: https://github.com/Miserlou/Zappa/issues/1554 by [virtualritz](https://github.com/virtualritz)

## Context
After using ``zappa init`` with all defaults, ``zappa deploy`` fails.

## Expected Behavior
``zappa deploy`` should succeed, initially, after a ``zappa init`` accepting all defaults.

## Actual Behavior
```
$ zappa deploy dev
Calling deploy for stage dev..
Warning! AWS Lambda may not be available in this AWS Region!
Warning! AWS API Gateway may not be available in this AWS Region!
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/zappa/cli.py", line 2693, in handle
    sys.exit(cli.handle())
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/zappa/cli.py", line 504, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/zappa/cli.py", line 530, in dispatch_command
    self.load_settings(self.vargs.get('settings_file'))
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/zappa/cli.py", line 2060, in load_settings
    xray_tracing=self.xray_tracing
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/zappa/core.py", line 293, in __init__
    self.lambda_client = self.boto_client('lambda', config=long_config)
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/zappa/core.py", line 323, in boto_client
    return self.boto_session.client(service, *args, **self.configure_boto_session_method_kwargs(service, kwargs))
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/client.py", line 285, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/client.py", line 358, in resolve
    service_name, region_name)
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/Users/moeller/.pyenv/versions/3.6.5/lib/python3.6/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

==============
```

## Steps to Reproduce
``zappa init`` (accept all defaults)
``zappa deploy dev``

## Your Environment

* Zappa 0.46.1
* MacOS 10.13.5, Python 3.6.5
* `pip freeze` (nothing – no deps)
* Your `zappa_settings.py`: 
```
{
    "dev": {
        "app_function": "app.init.app",
        "profile_name": "default",
        "project_name": "flask-lambda-la",
        "runtime": "python3.6",
        "s3_bucket": "zappa-3geposihd"
    },
    "dev_ap_northeast_1": {
        "aws_region": "ap-northeast-1",
        "extends": "dev"
    },
    "dev_ap_south_1": {
        "aws_region": "ap-south-1",
        "extends": "dev"
    },
    "dev_ap_southeast_1": {
        "aws_region": "ap-southeast-1",
        "extends": "dev"
    },
    "dev_ca_central_1": {
        "aws_region": "ca-central-1",
        "extends": "dev"
    },
    "dev_cn_north_1": {
        "aws_region": "cn-north-1",
        "extends": "dev"
    },
    "dev_eu_central_1": {
        "aws_region": "eu-central-1",
        "extends": "dev"
    },
    "dev_eu_west_1": {
        "aws_region": "eu-west-1",
        "extends": "dev"
    },
    "dev_sa_east_1": {
        "aws_region": "sa-east-1",
        "extends": "dev"
    },
    "dev_us_east_1": {
        "aws_region": "us-east-1",
        "extends": "dev"
    },
    "dev_us_west_1": {
        "aws_region": "us-west-1",
        "extends": "dev"
    }
}
```

**Comment by BloggingKIng** [comment]
How did you solved it?
