### ISSUE TITLE
[Migrated] update/deploy fails deployment check on non-WSGI application

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#610]
Originally from: https://github.com/Miserlou/Zappa/issues/1563 by [jwkvam](https://github.com/jwkvam)

## Context

When doing `zappa depoy` or `zappa update` I receive an error like this:
```
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 500 response code.
```
From the server I can get the following traceback:
```
[1531440426124] 'NoneType' object is not callable
[1531440426133] Traceback (most recent call last):
[1531440426133] File "/var/task/handler.py", line 508, in handler
[1531440426133] response = Response.from_app(self.wsgi_app, environ)
[1531440426133] File "/var/task/werkzeug/wrappers.py", line 939, in from_app
[1531440426133] return cls(*_run_wsgi_app(app, environ, buffered))
[1531440426133] File "/var/task/werkzeug/wrappers.py", line 59, in _run_wsgi_app
[1531440426133] return _run_wsgi_app(*args)
[1531440426133] File "/var/task/werkzeug/test.py", line 923, in run_wsgi_app
[1531440426133] app_rv = app(environ, start_response)
[1531440426133] File "/var/task/zappa/middleware.py", line 72, in __call__
[1531440426133] response = self.application(environ, encode_response)
[1531440426133] TypeError: 'NoneType' object is not callable
```

## Expected Behavior
No API Gateway request should be attempted for non-WSGI applications.

## Actual Behavior
Zappa attempts to touch the endpoint_url and fails because no app is setup.

## Possible Fix
Add in logic to `self.use_gateway` to also check for if an `app_function` is defined?

A workaround is to set `apigateway_enabled: false`, but it's hard to debug and figure out.

## Steps to Reproduce
1. Create a zappa application.
2. Don't set an `app_function`.
3. Zappa deploy.

## Your Environment
* Zappa version used:
0.46.1
* Operating System and Python version:
Docker with Python 3.6
* The output of `pip freeze`:
```
argcomplete==1.9.3
base58==1.0.0
boto3==1.7.30
botocore==1.10.56
certifi==2018.4.16
cfn-flip==1.0.3
chardet==3.0.4
click==6.7
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.7
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.20.0
placebo==0.8.1
psutil==5.4.6
python-dateutil==2.7.3
python-slugify==1.2.4
pytzdata==2018.5
PyYAML==3.12
requests==2.19.1
s3transfer==0.1.13
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.3.1
Unidecode==1.0.22
urllib3==1.23
Werkzeug==0.14.1
wsgi-request-logger==0.4.6
zappa==0.46.1
```
* Link to your project (optional):
* Your `zappa_settings.py`: 
```
    "staging": {
        "aws_region": "us-west-2",
        "memory_size": 512,
        "timeout_seconds": 300,
        "debug": true,
        "use_precompiled_packages": false,
        "delete_local_zip": false,
        "slim_handler": false,
        "runtime": "python3.6",
        "keep_warm": false,
        "manage_role": false,
      }
```

**Comment by duhaime** [comment]
Is anyone looking at these old issues? @jneves
