### ISSUE TITLE
[Migrated] Error when Zappa Deploy 

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#763]
Originally from: https://github.com/Miserlou/Zappa/issues/1901 by [taegsu](https://github.com/taegsu)

## Actual Behavior
Traceback (most recent call last):
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/core.py", line 924, in upload_to_s3
    self.s3_client.head_bucket(Bucket=bucket_name)
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/cli.py", line 2779, in handle
    sys.exit(cli.handle())
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/cli.py", line 509, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/cli.py", line 546, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/cli.py", line 723, in deploy
    self.zip_path, self.s3_bucket_name, disable_progress=self.disable_progress)
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/zappa/core.py", line 936, in upload_to_s3
    CreateBucketConfiguration={'LocationConstraint': self.aws_region},
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/gimtaegsu/Documents/Django-Zappa/.env/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: lasted version
* Operating System and Python version: MAC OS, Python3.7
* Your `zappa_settings.py`: {
    "dev": {
        "django_settings": "myproject.settings",
        "profile_name": "default",
	    "aws_region" : "ap-northeast-1",
	    "manage_roles" : false,
	    "role_name" : "my_arn_role_name",
	    "role_arn" : "my_role_arn_address",
        "project_name": "aws-django-board",
        "runtime": "python3.7",
        "s3_bucket": "lambda"
    }
}

**Comment by bes89** [comment]
Any update / workaround? I wanted to use zappa after some time, because the last time it was smooth, now I ran in this annyoing error.

**Comment by suavelad** [comment]
I am getting similar error, please any resolution yet ?

**Comment by monkut** [comment]
You could be setting the bucket to something already taken or controlled by another account.
Remember that s3 bucket names are globally unique.  Try adding a suffix/prefix to the bucket name configured in `zappa_settings.json`.
