### ISSUE TITLE
[Migrated] Localstack success?

### ISSUE THREAD

**Issue by jneves** [zappa/Zappa#798]
Originally from: https://github.com/Miserlou/Zappa/issues/1951 by [lucianthorr](https://github.com/lucianthorr)

I'd consider this more of a general question to the more experienced Zappa users out there.  Has anyone had success deploying to a localstack environment?
If so, I would love to see how you managed to make it work.  Zappa seems configured to work but from what I can tell, localstack is not sufficiently built out yet to make it work.

Thanks.

**Comment by VetoPlayer** [comment]
Not an experienced user here, but unfortunately I haven't been able to have the zappa <-> Localstack setup working as well.
During my last trial, an error occurs (500) when Zappa calls the [UpdateRestApi](https://docs.aws.amazon.com/cli/latest/reference/apigateway/update-rest-api.html) operation.
I wonder if it's possible to find a workaround for that.

 @lucianthorr are you experimenting the same issue?

For the sake of clarity and reproducibility, I'm using Localstack version 0.12.7, (If I remember correctly, I installed it using pip)
Zappa version is 0.52.0
My zappa_settings.json is the following:

```
{
    "dev": {
        "app_function": "app.app",
        "aws_region": "us-east-1",
        "profile_name": "default",
        "project_name": "simple-flask",
        "runtime": "python3.7",
        "s3_bucket": "zappa-6bm08lott",
        "aws_endpoint_urls": {
            "s3": "http://localhost:4566",
            "lambda": "http://localhost:4566",
            "apigateway": "http://localhost:4566",
            "iam": "http://localhost:4566",
            "cloudwatch": "http://localhost:4566",
            "acm": "http://localhost:4566",
            "logs": "http://localhost:4566",
            "route53": "http://localhost:4566",
            "sns": "http://localhost:4566",
            "sqs": "http://localhost:4566",
            "cloudformation": "http://localhost:4566",
            "dynamodb": "http://localhost:4566",
            "events": "http://localhost:4566"
        }
    }
}
```

Zappa error logged:

```
andrea@debian:~/Desktop/simple_flask$  . /home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/bin/activate
(simple_flask) andrea@debian:~/Desktop/simple_flask$ zappa deploy
Calling deploy for stage dev..
Creating simple-flask-dev-ZappaLambdaExecutionRole IAM Role..
Creating zappa-permissions policy on simple-flask-dev-ZappaLambdaExecutionRole IAM Role.
Downloading and installing dependencies..
 - pyyaml==5.4.1: Downloading
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 637k/637k [00:00<00:00, 2.58MB/s]
 - markupsafe==1.1.1: Downloading
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 27.5k/27.5k [00:00<00:00, 3.68MB/s]
Packaging project as zip.
Uploading simple-flask-dev-1616146627.zip (12.1MiB)..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 12.7M/12.7M [00:00<00:00, 22.3MB/s]
Scheduling..
Problem creating permission to invoke Lambda function
Scheduled simple-flask-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Uploading simple-flask-dev-template-1616146642.json (1.6KiB)..
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.63k/1.63k [00:00<00:00, 56.9kB/s]
Waiting for stack simple-flask-dev to create (this can take a bit)..
  0%|                                                                                                                      | 0/4 [00:03<?, ?res/s]
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/zappa/cli.py", line 2778, in handle
    sys.exit(cli.handle())
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/zappa/cli.py", line 512, in handle
    self.dispatch_command(self.command, stage)
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/zappa/cli.py", line 549, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/zappa/cli.py", line 828, in deploy
    self.zappa.add_binary_support(api_id=api_id, cors=self.cors)
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/zappa/core.py", line 1817, in add_binary_support
    'path': '/binaryMediaTypes/*~1*'
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (500) when calling the UpdateRestApi operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>


==============
```


Localstack Error Logged:
```
2021-03-19T09:33:21:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 14399.08218383789ms
2021-03-19T09:37:06:INFO:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:simple-flask-dev
2021-03-19T09:37:21:INFO:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:simple-flask-dev
2021-03-19T09:37:22:INFO:localstack.services.awslambda.lambda_api: The resource you requested does not exist.
```

**Comment by lucianthorr** [comment]
@VetoPlayer @jneves Thanks for tagging me.  This was definitely an interesting problem to work on but I haven't spent much time trying since that original post over a year ago.
From what I remember, it was a problem mostly with Localstack not being a realistic enough mock for Zappa.  Most specifically with setting up IAM policies and roles.

**Comment by techdragon** [comment]
There are a number of things zappa is using that might be non-functional in the basic free version of localstack. @VetoPlayer @lucianthorr Do you know which version (basic/free or paid/pro) of localstack you used for your testing?

**Comment by VetoPlayer** [comment]
Hi @techdragon 
I have been using localstack free version 0.12.6.1 and I can confirm what @lucianthorr is saying about IAM policies and roles not being realistic enough.

I experimented adding `"binary_support": false` into my zappa_settings.json in order to skip the UpdateRestApi call and I have been displayed the following error:

`Problem creating permission to invoke Lambda function`

Reporting the full log for completeness:

```
(simple_flask) andrea@debian:~/Desktop/simple_flask$ zappa deploy
Calling deploy for stage dev..
Creating simple-flask-dev-ZappaLambdaExecutionRole IAM Role..
Creating zappa-permissions policy on simple-flask-dev-ZappaLambdaExecutionRole IAM Role.
Downloading and installing dependencies..
 - pyyaml==5.4.1: Downloading
100%|████████████████████████████████████████████████████████████████████████████████████████| 637k/637k [00:00<00:00, 1.52MB/s]
 - markupsafe==1.1.1: Downloading
100%|██████████████████████████████████████████████████████████████████████████████████████| 27.5k/27.5k [00:00<00:00, 3.37MB/s]
Packaging project as zip.
Uploading simple-flask-dev-1616623701.zip (6.2MiB)..
100%|██████████████████████████████████████████████████████████████████████████████████████| 6.47M/6.47M [00:00<00:00, 18.5MB/s]
Scheduling..
Problem creating permission to invoke Lambda function
Scheduled simple-flask-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Uploading simple-flask-dev-template-1616623721.json (1.6KiB)..
100%|██████████████████████████████████████████████████████████████████████████████████████| 1.63k/1.63k [00:00<00:00, 73.3kB/s]
Waiting for stack simple-flask-dev to create (this can take a bit)..
  0%|                                                                                                    | 0/4 [00:03<?, ?res/s]
Deploying API Gateway..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f597adcc438>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='1o9celpbr0.execute-api.us-east-1.amazonaws.com', port=443): Max retries exceeded with url: /dev/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f597adcc438>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/zappa/cli.py", line 2778, in handle
    sys.exit(cli.handle())
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/zappa/cli.py", line 512, in handle
    self.dispatch_command(self.command, stage)
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/zappa/cli.py", line 549, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/zappa/cli.py", line 848, in deploy
    self.touch_endpoint(endpoint_url)
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/zappa/cli.py", line 2719, in touch_endpoint
    req = requests.get(endpoint_url + touch_path)
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/andrea/.local/share/virtualenvs/simple_flask-PRLPkRJQ/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='1o9celpbr0.execute-api.us-east-1.amazonaws.com', port=443): Max retries exceeded with url: /dev/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f597adcc438>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

On the localstack side instead: (just appending the log tail)

```
Ready.
2021-03-24T22:04:06:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 14138.473987579346ms
2021-03-24T22:08:21:INFO:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:simple-flask-dev
2021-03-24T22:08:41:INFO:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:simple-flask-dev
2021-03-24T22:08:41:INFO:localstack.services.awslambda.lambda_api: The resource you requested does not exist.
2021-03-24T22:11:53:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:simple-flask-dev"
2021-03-24T22:11:53:INFO:localstack.services.awslambda.lambda_executors: Determined main container target IP: 172.17.0.2
2021-03-24T22:11:53:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e AWS_REGION="$AWS_REGION" -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY"   --rm "lambci/lambda:20191117-python3.7" "handler.lambda_handler")";docker cp "/tmp/localstack/zipfile.ad880386/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
```

**Comment by lucianthorr** [comment]
@techdragon Same here.  I was using the free localstack

**Comment by monkut** [comment]
I use localstack, but only for it's other aws services support, and test my application against that without *deploying* the application to lambda in localstack.
