### ISSUE TITLE
SQLite 3.8.3 or later is required (found 3.7.17).

### ISSUE THREAD

**Issue by viktor-idenfy** [zappa/Zappa#973]
I keep getting the error when I call zappa deploy dev. The zappa tail provides this output:
SQLite 3.8.3 or later is required (found 3.7.17).
SQLite 3.8.3 or later is required (found 3.7.17).
Traceback (most recent call last):
  File "/var/task/handler.py", line 609, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
    handler = cls()
  File "/var/task/handler.py", line 146, in __init__
    wsgi_app_function = get_django_wsgi(self.settings.DJANGO_SETTINGS)
  File "/var/task/zappa/ext/django_zappa.py", line 20, in get_django_wsgi
    return get_wsgi_application()
  File "/var/task/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/var/task/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/task/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/var/task/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

My Django version is 3.15. What should I change?

**Comment by seanpar203** [comment]
I got this error when I was using >= 3.2 Django.

When I downgraded to 2.2 the error went away, although I still have plenty of other problems.

**Comment by tjquinn1** [comment]
This isn't a zappa issue. Newer versions of django require sqlite 3.8.3 but aws only installs 3.7.17 on the images used to create python lambdas. I tried to find a way to upgrade it and wasn't able to find one. Had to get an rds instance instead.

**Comment by edgarroman** [comment]
Possible workaround is to manually install the SQLite shared library in your project directory.  Additional instructions can be found at https://github.com/FlipperPA/django-s3-sqlite and the binaries are found under the `shared-objects` library.

**Comment by monkut** [comment]
as mentioned above, not a zappa issue, closing.
