### ISSUE TITLE
What would it take to integrate an old/legacy Django app into Zappa?

### ISSUE THREAD

**Issue by omar-enrique** [zappa/Zappa#996]
I apologize if an issue is not the right outlet for this type of question.

I see several examples for how to easily start your new Django project using Zappa through starting off with `zappa init` and allowing Zappa to take care of the whole deployment process of your Django app to AWS.  This becomes difficult for a Django project like mine, which is a legacy app that has a lot of complexity.  I am just wondering where I would begin to understand the refactoring I would have to do to our Django app to make it legible by Zappa, so it can integrate into a smooth deployment of Lambda functions, because I do not see documentation anywhere on the required format/directory structure for existing Django apps that someone might want to run serverlessly.  I ran zappa deploy in the root directory of my project and got the following error that the lamdbda functions it was trying to create were too large:

```
Traceback (most recent call last):
  File "/home/ubuntu/SkalaControl/env/lib/python3.7/site-packages/zappa/cli.py", line 896, in deploy
    function_name=self.lambda_name
  File "/home/ubuntu/SkalaControl/env/lib/python3.7/site-packages/zappa/core.py", line 1520, in get_lambda_function
    response = self.lambda_client.get_function(FunctionName=function_name)
  File "/home/ubuntu/SkalaControl/env/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/SkalaControl/env/lib/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetFunction operation: Function not found: arn:aws:lambda:us-east-1:253119149513:function:src-dev

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/SkalaControl/env/lib/python3.7/site-packages/zappa/cli.py", line 3422, in handle
    sys.exit(cli.handle())
  File "/home/ubuntu/SkalaControl/env/lib/python3.7/site-packages/zappa/cli.py", line 588, in handle
    self.dispatch_command(self.command, stage)
  File "/home/ubuntu/SkalaControl/env/lib/python3.7/site-packages/zappa/cli.py", line 630, in dispatch_command
    self.deploy(self.vargs["zip"], self.vargs["docker_image_uri"])
  File "/home/ubuntu/SkalaControl/env/lib/python3.7/site-packages/zappa/cli.py", line 930, in deploy
    self.lambda_arn = self.zappa.create_lambda_function(**kwargs)
  File "/home/ubuntu/SkalaControl/env/lib/python3.7/site-packages/zappa/core.py", line 1225, in create_lambda_function
    response = self.lambda_client.create_function(**kwargs)
  File "/home/ubuntu/SkalaControl/env/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/SkalaControl/env/lib/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Unzipped size must be smaller than 262144000 bytes
```

That's not surprising, but this isn't very helpful in diagnosing where the problem begins and what I have to do on my end to prepare my Django app to work with Zappa. Any help would be appreciated!

**Comment by weeksghost** [comment]
Hi,

Perhaps you could try the setting: 

`slim_handler: true`.

From the docs:

```
Useful if project >50M. Set true to just upload a small handler to Lambda and load actual project from S3 at runtime. Default false.
```

From personal experience I have moved a few small and medium projects over to Zappa successfully. What I decided was best for may projects, was to start with a brand new project, then migrate each app, dependency and settings one by one. I am in no way
saying this is necessary, but I'm very happy with the end result.

**Comment by omar-enrique** [comment]
@weeksghost, idk why I didn't think of that, but that's probably the best solution.  Start off a fresh new Zappa/Django app, and then move over each component one by one.  `slim_handler`: true is also helpful to know about, but it sounds better to not risk Zappa being confused by the large file stucture and make some Lambda functions that are too large and will have to be pulled apart anyway.  

Thank you for the recommendation!  Not sure if I should close this issue or keep the conversation going.

**Comment by monkut** [comment]
Issue appears to be resolved.
closing.
